changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ‼️ Breaking Changes & New Settings ⚙️
      labels:
        - breaking-change
        - config-change
    - title: Updated Dependencies 🧸
      labels:
        - dependencies
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - fix
        - bug
    - title: Internals/Plumbing 👩‍🔧
        - plumbing
        - tests
        - deployment
    - title: Other Changes
      labels:
        - "*"
