#!/bin/bash

# exit on errors
set -e

# import our ENV variables
# catch exits and give a friendly error message
function showerr {
    echo "Failed to load configuration! You may need to update your .env and quote values with special characters in them."
}
trap showerr EXIT
source .env
trap - EXIT

function clean {
    docker-compose stop
    docker-compose rm -f
}

function runweb {
    docker-compose run --rm web "$@"
    clean
}

function execdb {
    docker-compose exec db $@
}

function execweb {
    docker-compose exec web "$@"
}

function initdb {
    execweb python manage.py migrate
    execweb python manage.py initdb
}

function makeitblack {
    docker-compose run --rm web black celerywyrm bookwyrm
}

CMD=$1
shift

# show commands as they're executed
set -x

case "$CMD" in
    up)
        docker-compose up --build "$@"
        ;;
    run)
        docker-compose run --rm --service-ports web
        ;;
    initdb)
        initdb
        ;;
    resetdb)
        clean
        docker-compose up --build -d
        execdb dropdb -U ${POSTGRES_USER} ${POSTGRES_DB}
        execdb createdb -U ${POSTGRES_USER} ${POSTGRES_DB}
        initdb
        clean
        ;;
    makemigrations)
        execweb python manage.py makemigrations "$@"
        ;;
    migrate)
        execweb python manage.py rename_app fedireads bookwyrm
        execweb python manage.py migrate "$@"
        ;;
    bash)
        execweb bash
        ;;
    shell)
        execweb python manage.py shell
        ;;
    dbshell)
        execdb psql -U ${POSTGRES_USER} ${POSTGRES_DB}
        ;;
    restart_celery)
        docker-compose restart celery_worker
        ;;
    test)
        execweb coverage run --source='.' --omit="*/test*,celerywyrm*,bookwyrm/migrations/*" manage.py test "$@"
        ;;
    pytest)
        execweb pytest --no-cov-on-fail "$@"
        ;;
    test_report)
        execweb coverage report
        ;;
    collectstatic)
        execweb python manage.py collectstatic --no-input
        ;;
    makemessages)
        execweb django-admin makemessages --no-wrap --ignore=venv3 $@
        ;;
    compilemessages)
        execweb django-admin compilemessages --ignore venv3 $@
        ;;
    build)
        docker-compose build
        ;;
    clean)
        clean
        ;;
    black)
        makeitblack
        ;;
    populate_feeds)
        execweb python manage.py populate_streams
        ;;
    *)
        echo "Unrecognised command. Try: build, clean, up, initdb, resetdb, makemigrations, migrate, bash, shell, dbshell, restart_celery, test, pytest, test_report, black, populate_feeds"
        ;;
esac
