#!/bin/bash

# exit on errors
set -e

# import our ENV variables
# catch exits and give a friendly error message
function showerr {
    echo "Failed to load configuration! You may need to update your .env and quote values with special characters in them."
}
trap showerr EXIT
source .env
trap - EXIT

# show commands as they're executed
set -x

function execdb {
    docker-compose exec db $@
}

function execweb {
    docker-compose exec web "$@"
}

function initdb {
    execweb python manage.py migrate
    execweb python manage.py initdb
}

function makeitblack {
    runweb black celerywyrm bookwyrm
}

CMD=$1
shift

# show commands as they're executed
set -x

case "$CMD" in
    up)
        docker-compose up --build "$@"
        ;;
    run)
        docker-compose run --rm --service-ports web
        ;;
    initdb)
        initdb
        ;;
    makemigrations)
        execweb python manage.py makemigrations "$@"
        ;;
    migrate)
        execweb python manage.py rename_app fedireads bookwyrm
        execweb python manage.py migrate "$@"
        ;;
    bash)
        execweb bash
        ;;
    shell)
        execweb python manage.py shell
        ;;
    dbshell)
        execdb psql -U ${POSTGRES_USER} ${POSTGRES_DB}
        ;;
    restart_celery)
        docker-compose restart celery_worker
        ;;
    collectstatic)
        execweb python manage.py collectstatic --no-input
        ;;
    build)
        docker-compose build
        ;;
    update)
        git pull
        docker-compose exec web python manage.py migrate
        docker-compose exec web python manage.py collectstatic --no-input
        docker-compose restart
        ;;
    *)
        echo "Unrecognised command. Try: build, up, initdb, makemigrations, migrate, bash, shell, dbshell, restart_celery, update"
        ;;
esac
