""" comparing a free text format to the standardized one """
format_mappings = {
    "paperback": "Paperback",
    "soft": "Paperback",
    "pamphlet": "Paperback",
    "peperback": "Paperback",
    "tapa blanda": "Paperback",
    "turtleback": "Paperback",
    "pocket": "Paperback",
    "spiral": "Paperback",
    "ring": "Paperback",
    "平装": "Paperback",
    "简装": "Paperback",
    "hardcover": "Hardcover",
    "hardcocer": "Hardcover",
    "hardover": "Hardcover",
    "hardback": "Hardcover",
    "library": "Hardcover",
    "tapa dura": "Hardcover",
    "leather": "Hardcover",
    "clothbound": "Hardcover",
    "精装": "Hardcover",
    "ebook": "EBook",
    "e-book": "EBook",
    "digital": "EBook",
    "computer file": "EBook",
    "epub": "EBook",
    "online": "EBook",
    "pdf": "EBook",
    "elektronische": "EBook",
    "electronic": "EBook",
    "audiobook": "AudiobookFormat",
    "audio": "AudiobookFormat",
    "cd": "AudiobookFormat",
    "dvd": "AudiobookFormat",
    "mp3": "AudiobookFormat",
    "cassette": "AudiobookFormat",
    "kindle": "AudiobookFormat",
    "talking": "AudiobookFormat",
    "sound": "AudiobookFormat",
    "comic": "GraphicNovel",
    "graphic": "GraphicNovel",
}
