include /etc/nginx/conf.d/server_config;

server {
    access_log /var/log/nginx/access.log cache_log;
    listen 80;
    include /etc/nginx/conf.d/server_name;

    include /etc/nginx/conf.d/locations;
}
