# Generated by Django 3.0.3 on 2020-02-21 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0002_auto_20200219_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='content',
        ),
        migrations.RemoveField(
            model_name='federatedserver',
            name='content',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='content',
        ),
        migrations.RemoveField(
            model_name='shelfbook',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userrelationship',
            name='content',
        ),
        migrations.AddField(
            model_name='author',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='federatedserver',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shelf',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrelationship',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
