# Generated by Django 3.0.3 on 2020-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0006_auto_20200221_1702'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrelationship',
            constraint=models.UniqueConstraint(fields=('user_subject', 'user_object'), name='followers_unique'),
        ),
    ]
