# Generated by Django 3.0.7 on 2020-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0009_shelf_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='retry',
            field=models.BooleanField(default=False),
        ),
    ]
