# Generated by Django 3.0.7 on 2020-11-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0011_auto_20201113_1727"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("remote_id", models.CharField(max_length=255, null=True)),
                ("progress", models.IntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("PG", "page"), ("PCT", "percent")],
                        default="PG",
                        max_length=3,
                    ),
                ),
                (
                    "readthrough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bookwyrm.ReadThrough",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
