# Generated by Django 3.0.7 on 2020-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0011_auto_20201113_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_post_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers'), ('direct', 'Direct')], default='public', max_length=255),
        ),
    ]
