# Generated by Django 3.0.7 on 2020-11-23 20:44

import bookwyrm.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0011_auto_20201113_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='images',
            field=bookwyrm.utils.fields.ArrayField(base_field=models.ImageField(upload_to='status/'), default=list, size=None),
        ),
    ]
