# Generated by Django 3.0.7 on 2020-11-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0011_auto_20201113_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='origin_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
