# Generated by Django 3.0.3 on 2020-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0012_auto_20200308_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manually_approves_followers',
            field=models.BooleanField(default=False),
        ),
    ]
