# Generated by Django 3.0.3 on 2020-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0013_user_manually_approves_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='remote_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
