# Generated by Django 3.0.7 on 2020-11-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0013_book_origin_id"),
        ("bookwyrm", "0012_progressupdate"),
    ]

    operations = []
