# Generated by Django 3.0.7 on 2020-11-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0013_book_origin_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='Image',
        ),
    ]
