# Generated by Django 3.0.7 on 2020-12-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0012_user_default_post_privacy'),
        ('bookwyrm', '0013_book_origin_id'),
    ]

    operations = [
    ]
