# Generated by Django 3.0.7 on 2020-11-28 18:04

import bookwyrm.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0015_auto_20201128_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject_places',
            field=bookwyrm.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=bookwyrm.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
