# Generated by Django 3.0.3 on 2020-03-14 21:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0016_auto_20200313_1337'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userblocks',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user_subject=django.db.models.expressions.F('user_object')), name='userblocks_no_self'),
        ),
        migrations.AddConstraint(
            model_name='userfollowrequest',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user_subject=django.db.models.expressions.F('user_object')), name='userfollowrequest_no_self'),
        ),
        migrations.AddConstraint(
            model_name='userfollows',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user_subject=django.db.models.expressions.F('user_object')), name='userfollows_no_self'),
        ),
    ]
