# Generated by Django 3.0.7 on 2020-12-12 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0016_auto_20201211_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readthrough',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookwyrm.Edition'),
        ),
    ]
