# Generated by Django 3.0.7 on 2020-11-30 19:39

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0018_auto_20201130_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=bookwyrm.models.fields.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=bookwyrm.models.fields.TextField(default=''),
        ),
    ]
