# Generated by Django 3.0.7 on 2020-12-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0020_auto_20201208_0213'),
        ('bookwyrm', '0016_auto_20201211_2026'),
    ]

    operations = [
    ]
