# Generated by Django 3.0.3 on 2020-03-28 04:28

from django.db import migrations, models
import fedireads.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0020_auto_20200327_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goodreads_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subject_places',
            field=fedireads.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=fedireads.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='edition',
            name='physical_format',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='publishers',
            field=fedireads.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_file',
            field=models.CharField(choices=[('openlibrary', 'Openlibrary'), ('fedireads_connector', 'Fedireads Connector')], default='openlibrary', max_length=255),
        ),
    ]
