# Generated by Django 3.0.3 on 2020-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0021_auto_20200328_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='is_self',
        ),
        migrations.AddField(
            model_name='author',
            name='fedireads_key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_file',
            field=models.CharField(choices=[('openlibrary', 'Openlibrary'), ('self_connector', 'Self Connector'), ('fedireads_connector', 'Fedireads Connector')], default='openlibrary', max_length=255),
        ),
    ]
