# Generated by Django 3.0.7 on 2020-12-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0023_auto_20201214_0511'),
        ('bookwyrm', '0023_merge_20201216_0112'),
    ]

    operations = [
    ]
