# Generated by Django 3.0.3 on 2020-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0023_auto_20200328_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedserver',
            name='application_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
