# Generated by Django 3.0.7 on 2020-12-17 00:46

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0024_merge_20201216_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=bookwyrm.models.fields.HtmlField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=bookwyrm.models.fields.HtmlField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote',
            field=bookwyrm.models.fields.HtmlField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='content',
            field=bookwyrm.models.fields.HtmlField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=bookwyrm.models.fields.HtmlField(default=''),
        ),
    ]
