# Generated by Django 3.0.7 on 2020-12-20 20:07

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0026_status_content_warning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="summary",
            field=bookwyrm.models.fields.HtmlField(blank=True, null=True),
        ),
    ]
