# Generated by Django 3.0.7 on 2020-12-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0027_auto_20201220_2007"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author_text",
        ),
    ]
