# Generated by Django 3.0.7 on 2021-01-01 19:05

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0029_auto_20201221_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookwyrm.Review')),
            ],
            options={
                'abstract': False,
            },
            bases=('bookwyrm.review',),
        ),
    ]
