# Generated by Django 3.0.7 on 2021-01-05 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0032_auto_20210104_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinvite",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
