# Generated by Django 3.0.7 on 2021-01-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0033_siteinvite_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
