# Generated by Django 3.0.7 on 2021-01-11 17:18

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0034_importjob_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='edition_rank',
            field=bookwyrm.models.fields.IntegerField(default=0),
        ),
    ]
