# Generated by Django 3.0.3 on 2020-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0034_importjob_import_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='isbn',
            new_name='isbn_13',
        ),
        migrations.AddField(
            model_name='book',
            name='author_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='asin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
