# Generated by Django 3.0.7 on 2021-01-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0015_auto_20201128_0734'),
        ('bookwyrm', '0035_edition_edition_rank'),
    ]

    operations = [
    ]
