# Generated by Django 3.0.7 on 2021-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0036_annualgoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfbook',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
