# Generated by Django 3.0.3 on 2020-05-04 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0036_auto_20200503_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fedireads_key',
        ),
        migrations.RemoveField(
            model_name='book',
            name='fedireads_key',
        ),
        migrations.RemoveField(
            model_name='book',
            name='source_url',
        ),
        migrations.AddField(
            model_name='author',
            name='last_sync_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
