# Generated by Django 3.0.3 on 2020-05-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0037_auto_20200504_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
