# Generated by Django 3.0.7 on 2021-01-19 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0037_auto_20210118_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualgoal",
            name="goal",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
