# Generated by Django 3.0.3 on 2020-05-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0038_author_remote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='misc_identifiers',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='key_name',
        ),
    ]
