# Generated by Django 3.0.3 on 2020-05-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0039_auto_20200510_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actor',
        ),
        migrations.AddField(
            model_name='connector',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='federatedserver',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='readthrough',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shelf',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userblocks',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfollowrequest',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
