# Generated by Django 3.0.3 on 2020-05-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0040_auto_20200513_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remote_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
