# Generated by Django 3.0.7 on 2021-02-01 21:08

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0041_auto_20210131_1614"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ("-updated_date",)},
        ),
        migrations.AlterField(
            model_name="list",
            name="privacy",
            field=bookwyrm.models.fields.PrivacyField(
                choices=[
                    ("public", "Public"),
                    ("unlisted", "Unlisted"),
                    ("followers", "Followers"),
                    ("direct", "Direct"),
                ],
                default="public",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="privacy",
            field=bookwyrm.models.fields.PrivacyField(
                choices=[
                    ("public", "Public"),
                    ("unlisted", "Unlisted"),
                    ("followers", "Followers"),
                    ("direct", "Direct"),
                ],
                default="public",
                max_length=255,
            ),
        ),
    ]
