# Generated by Django 3.0.3 on 2020-05-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0041_user_remote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_type',
        ),
    ]
