# Generated by Django 3.0.7 on 2021-02-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0042_auto_20210201_2108"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listitem",
            old_name="added_by",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="shelfbook",
            old_name="added_by",
            new_name="user",
        ),
    ]
