# Generated by Django 3.0.3 on 2020-06-01 21:31

from django.db import migrations, models
import bookwyrm.models.site


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0042_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=bookwyrm.models.site.new_invite_code, max_length=32)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('use_limit', models.IntegerField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
            ],
        ),
    ]
