# Generated by Django 3.0.3 on 2020-06-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0043_siteinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinvite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
