# Generated by Django 3.0.7 on 2021-02-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0045_auto_20210210_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_post_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers'), ('direct', 'Direct')], default='public', max_length=255),
        ),
    ]
