# Generated by Django 3.0.7 on 2020-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0045_merge_20200810_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fedireads_user',
            new_name='bookwyrm_user',
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_file',
            field=models.CharField(choices=[('openlibrary', 'Openlibrary'), ('self_connector', 'Self Connector'), ('bookwyrm_connector', 'Bookwyrm Connector')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='1d8390fd.ngrok.io', max_length=100),
        ),
    ]
