# Generated by Django 3.0.7 on 2021-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0045_auto_20210210_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_policy",
            field=models.TextField(default="Add a privacy policy here."),
        ),
    ]
