# Generated by Django 3.0.7 on 2021-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0046_sitesettings_privacy_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="isbn_search_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
