# Generated by Django 3.0.7 on 2021-02-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0046_reviewrating"),
        ("bookwyrm", "0046_sitesettings_privacy_policy"),
    ]

    operations = []
