# Generated by Django 3.0.7 on 2020-09-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0047_auto_20200928_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedStatus',
            fields=[
                ('status_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookwyrm.Status')),
            ],
            options={
                'abstract': False,
            },
            bases=('bookwyrm.status',),
        ),
    ]
