# Generated by Django 3.0.7 on 2021-03-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0047_connector_isbn_search_url"),
        ("bookwyrm", "0047_merge_20210228_1839"),
    ]

    operations = []
