# Generated by Django 3.0.7 on 2021-03-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0049_auto_20210309_0156"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ("-created_date",)},
        ),
        migrations.AlterModelOptions(
            name="reportcomment",
            options={"ordering": ("-created_date",)},
        ),
        migrations.AlterField(
            model_name="report",
            name="statuses",
            field=models.ManyToManyField(blank=True, to="bookwyrm.Status"),
        ),
    ]
