# Generated by Django 3.0.7 on 2020-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0050_auto_20201002_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='BookWyrm', max_length=100),
        ),
    ]
