# Generated by Django 3.0.7 on 2021-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0051_auto_20210316_1950"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_goal",
            field=models.BooleanField(default=True),
        ),
    ]
