# Generated by Django 3.0.7 on 2020-10-06 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0052_auto_20201005_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='deleted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
