# Generated by Django 3.0.7 on 2020-10-14 17:00

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0052_auto_20201005_2145'),
    ]

    operations = [
        TrigramExtension()
    ]
