# Generated by Django 3.0.7 on 2020-10-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0052_auto_20201005_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(default='/static/images/favicon.ico', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(default='/static/images/logo.png', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_small',
            field=models.ImageField(default='/static/images/logo-small.png', upload_to='static/images/'),
        ),
    ]
