# Generated by Django 3.0.7 on 2020-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0053_auto_20201006_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='deleted_date',
            field=models.DateTimeField(),
        ),
    ]
