# Generated by Django 3.0.7 on 2020-10-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0053_auto_20201014_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblocks',
            name='relationship_id',
        ),
        migrations.RemoveField(
            model_name='userfollowrequest',
            name='relationship_id',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='relationship_id',
        ),
    ]
