# Generated by Django 3.0.7 on 2020-10-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0054_auto_20201016_1707'),
        ('bookwyrm', '0054_auto_20201016_2359'),
    ]

    operations = [
    ]
