# Generated by Django 3.0.7 on 2020-10-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0055_merge_20201017_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
