# Generated by Django 3.0.7 on 2020-10-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0057_auto_20201026_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='import_status',
        ),
    ]
