# Generated by Django 3.1.6 on 2021-03-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0057_user_discoverable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"ordering": ("-published_date",)},
        ),
    ]
