# Generated by Django 3.0.7 on 2020-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0058_remove_importjob_import_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='include_reviews',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers'), ('direct', 'Direct')], default='public', max_length=255),
        ),
    ]
