# Generated by Django 3.1.6 on 2021-03-30 19:58

from django.conf import settings
from django.db import migrations
import django.db.models.deletion

import bookwyrm.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0059_user_preferred_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="deleted_date",
        ),
        migrations.AlterField(
            model_name="boost",
            name="boosted_status",
            field=bookwyrm.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boosters",
                to="bookwyrm.status",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="status",
            field=bookwyrm.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookwyrm.status"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=bookwyrm.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="reply_parent",
            field=bookwyrm.models.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookwyrm.status",
            ),
        ),
    ]
