# Generated by Django 3.0.7 on 2020-10-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0059_auto_20201030_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='federated_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookwyrm.FederatedServer'),
        ),
    ]
