# Generated by Django 3.0.7 on 2020-10-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0060_auto_20201030_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneratedStatus',
            new_name='GeneratedNote',
        ),
    ]
