# Generated by Django 3.1.6 on 2021-04-02 14:35

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0060_siteinvite_invitees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="outbox",
            field=bookwyrm.models.fields.RemoteIdField(
                max_length=255,
                null=True,
                unique=True,
                validators=[bookwyrm.models.fields.validate_remote_id],
            ),
        ),
    ]
