# Generated by Django 3.1.6 on 2021-03-30 20:17

from django.db import migrations


def delete_statuses(app_registry, schema_editor):
    """ turn the "deleted" statuses into deleted statuses """
    db_alias = schema_editor.connection.alias
    statuses = (
        app_registry.get_model("bookwyrm", "Status")
        .objects.using(db_alias)
        .filter(deleted=True)
    )
    statuses.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0060_auto_20210330_1958"),
    ]

    operations = [
        migrations.RunPython(delete_statuses),
    ]
