# Generated by Django 3.0.7 on 2020-10-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0061_auto_20201030_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='max_query_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='politeness_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='search_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
