# Generated by Django 3.1.6 on 2021-03-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0061_auto_20210330_2017"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="deleted",
        ),
    ]
