# Generated by Django 3.1.6 on 2021-04-08 00:32

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0061_auto_20210402_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_published_year_only',
            field=bookwyrm.models.fields.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year_only',
            field=bookwyrm.models.fields.BooleanField(default=False),
        ),
    ]
