# Generated by Django 3.1.6 on 2021-04-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0061_auto_20210402_1435"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federatedserver",
            name="status",
            field=models.CharField(
                choices=[("federated", "Federated"), ("blocked", "Blocked")],
                default="federated",
                max_length=255,
            ),
        ),
    ]
