# Generated by Django 3.1.6 on 2021-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0062_auto_20210407_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="federatedserver",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="federatedserver",
            name="application_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="federatedserver",
            name="application_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="federatedserver",
            name="status",
            field=models.CharField(
                choices=[("federated", "Federated"), ("blocked", "Blocked")],
                default="federated",
                max_length=255,
            ),
        ),
    ]
