# Generated by Django 3.1.6 on 2021-04-06 17:38

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0062_auto_20210406_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="inventaire_id",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="inventaire_id",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
