# Generated by Django 3.1.6 on 2021-04-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0062_auto_20210405_2249'),
        ('bookwyrm', '0062_auto_20210407_1545'),
    ]

    operations = [
    ]
