# Generated by Django 3.0.7 on 2020-11-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0062_auto_20201031_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
