# Generated by Django 3.1.8 on 2021-04-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0063_auto_20210408_1556"),
        ("bookwyrm", "0063_auto_20210407_1827"),
    ]

    operations = []
