# Generated by Django 3.1.6 on 2021-04-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0063_auto_20210408_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="book_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookwyrm.list"
            ),
        ),
        migrations.AlterField(
            model_name="shelfbook",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bookwyrm.shelf"
            ),
        ),
    ]
