# Generated by Django 3.0.7 on 2020-11-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0063_user_last_active_date'),
        ('bookwyrm', '0063_auto_20201101_1758'),
    ]

    operations = [
    ]
