# Generated by Django 3.1.8 on 2021-04-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0064_auto_20210408_2208"),
        ("bookwyrm", "0064_merge_20210410_1633"),
    ]

    operations = []
