# Generated by Django 3.1.8 on 2021-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0065_merge_20210411_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self_deletion", "Self Deletion"),
                    ("moderator_deletion", "Moderator Deletion"),
                    ("domain_block", "Domain Block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
