# Generated by Django 3.1.6 on 2021-04-08 16:15

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0067_denullify_list_item_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="order",
            field=bookwyrm.models.fields.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="listitem",
            unique_together={("order", "book_list"), ("book", "book_list")},
        ),
    ]
