# Generated by Django 3.1.8 on 2021-04-22 16:04

import bookwyrm.models.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0068_ordering_for_list_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="last_edited_by",
            field=bookwyrm.models.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="last_edited_by",
            field=bookwyrm.models.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
