# Generated by Django 3.2 on 2021-04-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0063_auto_20210407_0045"),
        ("bookwyrm", "0070_auto_20210423_0121"),
    ]

    operations = []
