# Generated by Django 3.2 on 2021-04-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0071_merge_0063_auto_20210407_0045_0070_auto_20210423_0121"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="default_edition",
        ),
    ]
