# Generated by Django 3.2 on 2021-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0072_remove_work_default_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_item",
            field=models.TextField(blank=True, null=True),
        ),
    ]
