# Generated by Django 3.2 on 2021-05-21 00:17

from django.db import migrations
import bookwyrm


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0075_announcement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edition",
            old_name="physical_format",
            new_name="physical_format_detail",
        ),
        migrations.AddField(
            model_name="edition",
            name="physical_format",
            field=bookwyrm.models.fields.CharField(
                blank=True,
                choices=[
                    ("AudiobookFormat", "Audiobookformat"),
                    ("EBook", "Ebook"),
                    ("GraphicNovel", "Graphicnovel"),
                    ("Hardcover", "Hardcover"),
                    ("Paperback", "Paperback"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
