# Generated by Django 3.2 on 2021-05-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0074_generatednote_note_type"),
        ("bookwyrm", "0075_announcement"),
    ]

    operations = []
