# Generated by Django 3.2 on 2021-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0075_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="previews/covers/"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="previews/logos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="previews/avatars/"
            ),
        ),
    ]
