# Generated by Django 3.2.4 on 2021-06-18 22:38

import bookwyrm.models.fields
from django.db import migrations


def forward_func(apps, schema_editor):
    """set the generated note types"""
    db_alias = schema_editor.connection.alias

    generated_notes = apps.get_model("bookwyrm", "GeneratedNote").objects.using(
        db_alias
    )

    for note in generated_notes:
        if note.content and "started" in note.content:
            note.note_type = "READING"
        elif note.content and "finished" in note.content:
            note.note_type = "READ"
        elif note.content and "wants" in note.content:
            note.note_type = "TO_READ"
        else:
            note.note_type = "GOAL"
        if note.note_type != "GOAL":
            note.content = None
        note.save()


def reverse_func(apps, schema_editor):
    """nothing to do here"""
    db_alias = schema_editor.connection.alias

    generated_notes = apps.get_model("bookwyrm", "GeneratedNote").objects.using(
        db_alias
    )

    for note in generated_notes:
        message = {
            "TO_READ": "wants to read",
            "READING": "started reading",
            "READ": "finished reading",
        }
        if note.note_type in message:
            note.content = message[note.note_type]
            note.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0076_preview_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednote",
            name="note_type",
            field=bookwyrm.models.fields.CharField(
                choices=[
                    ("TO_READ", "To Read"),
                    ("READING", "Reading"),
                    ("READ", "Read"),
                    ("GOAL", "Goal"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(forward_func, reverse_func),
        migrations.AlterField(
            model_name="generatednote",
            name="note_type",
            field=bookwyrm.models.fields.CharField(
                choices=[
                    ("TO_READ", "To Read"),
                    ("READING", "Reading"),
                    ("READ", "Read"),
                    ("GOAL", "Goal"),
                ],
                max_length=255,
            ),
        ),
    ]
