# Generated by Django 3.2.4 on 2021-07-19 21:14

from django.db import connection, migrations, models
import django.db.models.deletion
from psycopg2.extras import execute_values


def forward_func(apps, schema_editor):
    """set the generated note types"""
    db_alias = schema_editor.connection.alias

    to_read_statuses = (
        apps.get_model("bookwyrm", "GeneratedNote")
        .objects.using(db_alias)
        .filter(content__contains="wants to read")
    )
    reading_statuses = (
        apps.get_model("bookwyrm", "GeneratedNote")
        .objects.using(db_alias)
        .filter(content__contains="started reading")
    )
    read_statuses = (
        apps.get_model("bookwyrm", "GeneratedNote")
        .objects.using(db_alias)
        .filter(content__contains="finished reading")
    )

    for (notes, model_name) in [
        (to_read_statuses, "toread"),
        (reading_statuses, "reading"),
        (read_statuses, "read"),
    ]:
        with connection.cursor() as cursor:
            values = [(s.id,) for s in notes]
            execute_values(
                cursor,
                """
    INSERT INTO bookwyrm_{}(generatednote_ptr_id)
    values %s""".format(
                    model_name
                ),
                values,
            )
    # erase invalid strings in "content" field
    apps.get_model("bookwyrm", "ToRead").objects.using(db_alias).all().update(
        content=None
    )
    apps.get_model("bookwyrm", "Reading").objects.using(db_alias).all().update(
        content=None
    )
    apps.get_model("bookwyrm", "Read").objects.using(db_alias).all().update(
        content=None
    )


def reverse_func(apps, schema_editor):
    """add back the default generated content"""
    db_alias = schema_editor.connection.alias

    apps.get_model("bookwyrm", "ToRead").objects.using(db_alias).update(
        content="wants to read"
    )
    apps.get_model("bookwyrm", "Reading").objects.using(db_alias).update(
        content="started reading"
    )
    apps.get_model("bookwyrm", "Read").objects.using(db_alias).update(
        content="finished reading"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0077_auto_20210623_2155"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalStatus",
            fields=[
                (
                    "generatednote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.generatednote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.generatednote",),
        ),
        migrations.CreateModel(
            name="ReadingStatus",
            fields=[
                (
                    "generatednote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.generatednote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.generatednote",),
        ),
        migrations.CreateModel(
            name="ReadStatus",
            fields=[
                (
                    "generatednote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.generatednote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.generatednote",),
        ),
        migrations.CreateModel(
            name="ToReadStatus",
            fields=[
                (
                    "generatednote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.generatednote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.generatednote",),
        ),
    ]
