# Generated by Django 3.2.4 on 2021-06-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0077_auto_20210623_2155"),
        ("bookwyrm", "0077_generatednote_note_type"),
    ]

    operations = []
