# Generated by Django 3.2.4 on 2021-08-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0046_user_default_post_privacy"),
        ("bookwyrm", "0078_add_shelved_date"),
    ]

    operations = []
