# Generated by Django 3.2.4 on 2021-07-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0078_add_shelved_date"),
        ("bookwyrm", "0078_goalstatus_readingstatus_readstatus_toreadstatus"),
    ]

    operations = []
