# Generated by Django 3.2.4 on 2021-07-29 00:19

import bookwyrm.models.fields
from django.db import migrations


def forward_func(apps, schema_editor):
    """set the generated note types"""
    db_alias = schema_editor.connection.alias

    to_read_statuses = (
        apps.get_model("bookwyrm", "GeneratedNote")
        .objects.using(db_alias)
        .filter(content__contains="wants to read")
    )
    reading_statuses = (
        apps.get_model("bookwyrm", "GeneratedNote")
        .objects.using(db_alias)
        .filter(content__contains="started reading")
    )
    read_statuses = (
        apps.get_model("bookwyrm", "GeneratedNote")
        .objects.using(db_alias)
        .filter(content__contains="finished reading")
    )

class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0078_add_shelved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfbook',
            options={'ordering': ('-shelved_date', '-created_date', '-updated_date')},
        ),
        migrations.AddField(
            model_name='comment',
            name='state_change',
            field=bookwyrm.models.fields.CharField(blank=True, choices=[('toRead', 'Toread'), ('reading', 'Reading'), ('read', 'Read')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='state_change',
            field=bookwyrm.models.fields.CharField(blank=True, choices=[('toRead', 'Toread'), ('reading', 'Reading'), ('read', 'Read')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='state_change',
            field=bookwyrm.models.fields.CharField(blank=True, choices=[('toRead', 'Toread'), ('reading', 'Reading'), ('read', 'Read')], max_length=255, null=True),
        ),
    ]
