# Generated by Django 3.2.4 on 2021-08-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0079_merge_20210804_1746"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shelfbook",
            options={"ordering": ("-shelved_date", "-created_date", "-updated_date")},
        ),
    ]
