# Generated by Django 3.2.4 on 2021-08-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0077_rename_physical_format_edition_physical_format_detail"),
        ("bookwyrm", "0079_merge_20210804_1746"),
    ]

    operations = []
