# Generated by Django 3.2.4 on 2021-08-06 23:24

import bookwyrm.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0081_alter_user_last_active_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="require_confirm_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                default=bookwyrm.models.base_model.new_access_code, max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("self_deletion", "Self Deletion"),
                    ("moderator_deletion", "Moderator Deletion"),
                    ("domain_block", "Domain Block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("self_deletion", "Self Deletion"),
                    ("moderator_deletion", "Moderator Deletion"),
                    ("domain_block", "Domain Block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
