# Generated by Django 3.2.4 on 2021-08-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0082_auto_20210806_2324"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitem",
            name="book_guess",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_guess",
                to="bookwyrm.book",
            ),
        ),
    ]
