# Generated by Django 3.2.4 on 2021-08-17 19:16

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0083_auto_20210816_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reading_status",
            field=bookwyrm.models.fields.CharField(
                blank=True,
                choices=[
                    ("to-read", "To-Read"),
                    ("reading", "Reading"),
                    ("read", "Read"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="reading_status",
            field=bookwyrm.models.fields.CharField(
                blank=True,
                choices=[
                    ("to-read", "To-Read"),
                    ("reading", "Reading"),
                    ("read", "Read"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reading_status",
            field=bookwyrm.models.fields.CharField(
                blank=True,
                choices=[
                    ("to-read", "To-Read"),
                    ("reading", "Reading"),
                    ("read", "Read"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
