# Generated by Django 3.2.4 on 2021-08-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0084_auto_20210817_1916"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_lists",
            field=models.ManyToManyField(
                related_name="saved_lists", to="bookwyrm.List"
            ),
        ),
    ]
