# Generated by Django 3.2.4 on 2021-08-27 17:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0085_user_saved_lists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readthrough",
            options={"ordering": ("-start_date",)},
        ),
        migrations.AddConstraint(
            model_name="readthrough",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("finish_date__gte", django.db.models.expressions.F("start_date"))
                ),
                name="chronology",
            ),
        ),
    ]
