# Generated by Django 3.2.4 on 2021-08-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0086_auto_20210827_1727"),
        ("bookwyrm", "0086_auto_20210828_1724"),
    ]

    operations = []
