# Generated by Django 3.2.4 on 2021-09-05 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0087_merge_0086_auto_20210827_1727_0086_auto_20210828_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="position",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="position_mode",
            field=models.CharField(
                blank=True,
                choices=[("PG", "page"), ("PCT", "percent")],
                default="PG",
                max_length=3,
                null=True,
            ),
        ),
    ]
