# Generated by Django 3.2.4 on 2021-09-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0088_auto_20210905_2233"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_suggested_users",
            field=models.BooleanField(default=True),
        ),
    ]
