# Generated by Django 3.2.4 on 2021-09-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0080_merge_20210804_2114"),
        ("bookwyrm", "0088_auto_20210905_2233"),
    ]

    operations = []
