# Generated by Django 3.2.4 on 2021-09-07 19:46

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0089_merge_20210907_0514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="physical_format",
            field=bookwyrm.models.fields.CharField(
                blank=True,
                choices=[
                    ("AudiobookFormat", "Audiobook"),
                    ("EBook", "eBook"),
                    ("GraphicNovel", "Graphic novel"),
                    ("Hardcover", "Hardcover"),
                    ("Paperback", "Paperback"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
