# Generated by Django 3.2.4 on 2021-09-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0089_user_show_suggested_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("self_deletion", "Self Deletion"),
                    ("moderator_suspension", "Moderator Suspension"),
                    ("moderator_deletion", "Moderator Deletion"),
                    ("domain_block", "Domain Block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("self_deletion", "Self Deletion"),
                    ("moderator_suspension", "Moderator Suspension"),
                    ("moderator_deletion", "Moderator Deletion"),
                    ("domain_block", "Domain Block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
