# Generated by Django 3.2.4 on 2021-09-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0090_auto_20210908_2346"),
        ("bookwyrm", "0090_emailblocklist"),
    ]

    operations = []
