# Generated by Django 3.2.4 on 2021-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0091_merge_0090_auto_20210908_2346_0090_emailblocklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="instance_short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
