# Generated by Django 3.2.4 on 2021-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0092_sitesettings_instance_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="instance_short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
