# Generated by Django 3.2.4 on 2021-09-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0094_auto_20210911_1550"),
        ("bookwyrm", "0094_importitem_book_guess"),
    ]

    operations = []
