# Generated by Django 3.2.4 on 2021-09-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0096_merge_20210912_0044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connector",
            name="local",
        ),
    ]
