# Generated by Django 3.2.4 on 2021-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0096_merge_20210912_0044"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBlocklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("address", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_date",),
            },
        ),
        migrations.AddField(
            model_name="emailblocklist",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
