# Generated by Django 3.2.4 on 2021-09-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0097_auto_20210917_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="invite_request_text",
            field=models.TextField(
                default="If your request is approved, you will receive an email with a registration link."
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="registration_closed_text",
            field=models.TextField(
                default='We aren\'t taking new users at this time. You can find an open instance at <a href="https://joinbookwyrm.com/instances">joinbookwyrm.com/instances</a>.'
            ),
        ),
    ]
