# Generated by Django 3.2.4 on 2021-09-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0098_auto_20210918_2238"),
    ]

    operations = [
        migrations.AddField(
            model_name="readthrough",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
