# Generated by Django 3.2.5 on 2021-09-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0102_remove_connector_local"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connector",
            name="local",
        ),
    ]
