# Generated by Django 3.2.5 on 2021-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0105_alter_connector_connector_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-us", "English"),
                    ("de-de", "German"),
                    ("es", "Spanish"),
                    ("fr-fr", "French"),
                    ("zh-hans", "Simplified Chinese"),
                    ("zh-hant", "Traditional Chinese"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
