# Generated by Django 3.2.5 on 2021-10-10 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0106_auto_20211005_0935"),
        ("bookwyrm", "0106_user_preferred_language"),
    ]

    operations = []
