# Generated by Django 3.2.5 on 2021-10-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0108_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
