# Generated by Django 3.2.5 on 2021-10-15 01:28

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0109_status_edited_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="raw_quote",
            field=bookwyrm.models.fields.HtmlField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="raw_content",
            field=bookwyrm.models.fields.HtmlField(blank=True, null=True),
        ),
    ]
