# Generated by Django 3.2.5 on 2021-10-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0109_status_edited_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="raw_quote",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="raw_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
