# Generated by Django 3.2.5 on 2021-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0112_auto_20211022_0844"),
    ]

    operations = [
        migrations.AddField(
            model_name="importitem",
            name="normalized_data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importjob",
            name="mappings",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
