# Generated by Django 3.2.5 on 2021-11-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0113_auto_20211110_2104"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="source",
            field=models.CharField(default="Import", max_length=100),
            preserve_default=False,
        ),
    ]
