# Generated by Django 3.2.5 on 2021-11-14 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0115_importitem_linked_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='task_id',
        ),
        migrations.AddField(
            model_name='importjob',
            name='completed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
