# Generated by Django 3.2.5 on 2021-11-24 10:15

import bookwyrm.models.user
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0118_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feed_status_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("review", "Reviews"),
                        ("comment", "Comments"),
                        ("quotation", "Quotations"),
                        ("everything", "Everything else"),
                    ],
                    max_length=10,
                ),
                default=bookwyrm.models.user.get_feed_filter_choices,
                size=8,
            ),
        ),
    ]
