# Generated by Django 3.2.5 on 2021-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0120_list_embed_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="summary_keys",
            field=models.JSONField(null=True),
        ),
    ]
