# Generated by Django 3.2.10 on 2022-01-17 17:16

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0128_merge_0126_auto_20220112_2315_0127_auto_20220110_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="filelink",
            name="availability",
            field=bookwyrm.models.fields.CharField(
                choices=[
                    ("free", "Free"),
                    ("purchase", "Purchasable"),
                    ("loan", "Available for loan"),
                ],
                default="free",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="filelink",
            name="filetype",
            field=bookwyrm.models.fields.CharField(max_length=50),
        ),
    ]
