# Generated by Django 3.2.10 on 2022-01-17 17:03

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0128_merge_0126_auto_20220112_2315_0127_auto_20220110_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelink',
            name='is_purchase',
            field=bookwyrm.models.fields.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filelink',
            name='filetype',
            field=bookwyrm.models.fields.CharField(max_length=50),
        ),
    ]
