# Generated by Django 3.2.10 on 2022-01-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0130_alter_listitem_notes"),
        ("bookwyrm", "0130_alter_user_preferred_language"),
    ]

    operations = []
