# Generated by Django 3.2.10 on 2022-01-30 19:38

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0131_merge_20220125_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="viaf",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="wikidata",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="viaf",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wikidata",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
