# Generated by Django 3.2.11 on 2022-02-04 20:06

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0132_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="notes",
            field=bookwyrm.models.fields.HtmlField(
                blank=True, max_length=300, null=True
            ),
        ),
    ]
