# Generated by Django 3.2.11 on 2022-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0133_alter_listitem_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("white-ter", "None"),
                    ("primary-light", "Primary"),
                    ("success-light", "Success"),
                    ("link-light", "Link"),
                    ("warning-light", "Warning"),
                    ("danger-light", "Danger"),
                ],
                default="white-ter",
                max_length=20,
            ),
        ),
    ]
