# Generated by Django 3.2.12 on 2022-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0136_auto_20220217_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="allow_registration",
            field=models.BooleanField(default=False),
        ),
    ]
