# Generated by Django 3.2.12 on 2022-02-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0137_alter_sitesettings_allow_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoMod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string_match", models.CharField(max_length=200, unique=True)),
                ("flag_users", models.BooleanField(default=True)),
                ("flag_statuses", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
