# Generated by Django 3.2.12 on 2022-02-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0139_report_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="statuses",
        ),
    ]
