# Generated by Django 3.2.12 on 2022-02-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0140_remove_report_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookwyrm.status",
            ),
        ),
    ]
