# Generated by Django 3.2.12 on 2022-02-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0134_alter_stopped_reading'),
        ('bookwyrm', '0141_alter_report_status'),
    ]

    operations = [
    ]
