# Generated by Django 3.2.12 on 2022-02-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0142_auto_20220227_1752"),
        ("bookwyrm", "0142_user_hide_follows"),
    ]

    operations = []
