# Generated by Django 3.2.12 on 2022-03-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0142_merge_20220225_2103'),
        ('bookwyrm', '0144_alter_announcement_display_type'),
    ]

    operations = [
    ]
