# Generated by Django 3.2.12 on 2022-03-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0144_alter_announcement_display_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="version",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
