# Generated by Django 3.2.12 on 2022-03-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0144_alter_announcement_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.TextField(blank=True, max_length=500, verbose_name='question'),
        ),
    ]
