# Generated by Django 3.2.12 on 2022-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0145_auto_20220307_2025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="invite_question_text",
            field=models.CharField(
                blank=True,
                default="What is your favourite book?",
                max_length=255,
                null=True,
            ),
        ),
    ]
