# Generated by Django 3.2.12 on 2022-03-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0146_auto_20220316_2320"),
        ("bookwyrm", "0147_alter_user_preferred_language"),
    ]

    operations = []
