# Generated by Django 3.2.12 on 2022-03-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0147_alter_user_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='question',
            new_name='answer',
        ),
    ]
