# Generated by Django 3.2.13 on 2022-05-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0148_alter_user_preferred_language"),
        ("bookwyrm", "0148_merge_20220326_2006"),
    ]

    operations = []
