# Generated by Django 3.2.12 on 2022-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0148_rename_question_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviterequest',
            name='answer',
            field=models.TextField(default='yyyyy', max_length=512),
            preserve_default=False,
        ),
    ]
