# Generated by Django 3.2.12 on 2022-04-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0148_alter_user_preferred_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="related_book",
        ),
    ]
