# Generated by Django 3.2.13 on 2022-05-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0149_merge_20220526_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="readthrough",
            name="stopped_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
