# Generated by Django 3.2.12 on 2022-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0149_inviterequest_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviterequest',
            name='answer',
            field=models.TextField(max_length=50),
        ),
    ]
