# Generated by Django 3.2.13 on 2022-06-13 01:59

import bookwyrm.models.fields
from django.db import migrations


def existing_users_default(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    user_model = apps.get_model("bookwyrm", "User")
    user_model.objects.using(db_alias).filter(local=True).update(show_guided_tour=False)


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0150_readthrough_stopped_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_guided_tour",
            field=bookwyrm.models.fields.BooleanField(default=True),
        ),
        migrations.RunPython(existing_users_default, migrations.RunPython.noop),
    ]
