# Generated by Django 3.2.13 on 2022-06-13 01:59

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0150_readthrough_stopped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_guided_tour',
            field=bookwyrm.models.fields.BooleanField(default=True),
        ),
    ]
