# Generated by Django 3.2.13 on 2022-07-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0151_auto_20220705_0049"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_type_valid",
        ),
    ]
