# Generated by Django 3.2.13 on 2022-07-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0152_alter_report_user"),
        ("bookwyrm", "0152_remove_notification_notification_type_valid"),
    ]

    operations = []
