# Generated by Django 3.2.14 on 2022-07-09 23:33

from django.db import migrations, models


def existing_users_default(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    user_model = apps.get_model("bookwyrm", "User")
    user_model.objects.using(db_alias).filter(local=True).update(show_guided_tour=False)


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0154_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_guided_tour",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(existing_users_default, migrations.RunPython.noop),
    ]
