# Generated by Django 3.2.14 on 2022-07-09 21:21

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0154_bookauthor"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="new_authors",
            field=bookwyrm.models.fields.ManyToManyField(
                related_name="new_authors",
                through="bookwyrm.BookAuthor",
                to="bookwyrm.Author",
            ),
        ),
        migrations.RunSQL(
            sql="""
INSERT INTO bookwyrm_bookauthor (id, book_id, author_id, created_date, updated_date, author_type)
SELECT id, book_id, author_id, NOW(), NOW(), 'author' from bookwyrm_book_authors;
            """,
            reverse_sql="""
INSERT INTO bookwyrm_book_authors (id, book_id, author_id)
SELECT id, book_id, author_id from bookwyrm_bookauthor;
            """,
        ),
        migrations.RemoveField(model_name="book", name="authors"),
        migrations.RenameField(
            model_name="book", old_name="new_authors", new_name="authors"
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=bookwyrm.models.fields.ManyToManyField(
                through="bookwyrm.BookAuthor", to="bookwyrm.Author"
            ),
        ),
    ]
