# Generated by Django 3.2.14 on 2022-07-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0155_book_new_authors"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bookauthor",
            table="bookwyrm_book_authors",
        ),
    ]
