# Generated by Django 3.2.14 on 2022-08-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0155_auto_20220720_1557"),
        ("bookwyrm", "0156_alter_user_preferred_language"),
    ]

    operations = []
