# Generated by Django 3.2.14 on 2022-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0157_merge_20220804_2030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, null=True, to="bookwyrm.Genre"),
        ),
    ]
