# Generated by Django 3.2.15 on 2022-09-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0158_alter_book_genres"),
        ("bookwyrm", "0158_auto_20220919_1634"),
    ]

    operations = []
