# Generated by Django 3.2.15 on 2022-09-26 03:07

import bookwyrm.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0159_merge_0158_alter_book_genres_0158_auto_20220919_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.ManyToManyField(blank=True, to="bookwyrm.Genre"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=bookwyrm.models.fields.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre_name",
            field=bookwyrm.models.fields.CharField(max_length=40),
        ),
    ]
