# Generated by Django 3.2.15 on 2022-11-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0159_auto_20220924_0634"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_reactivation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="connector",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("self_deletion", "Self deletion"),
                    ("self_deactivation", "Self deactivation"),
                    ("moderator_suspension", "Moderator suspension"),
                    ("moderator_deletion", "Moderator deletion"),
                    ("domain_block", "Domain block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("self_deletion", "Self deletion"),
                    ("self_deactivation", "Self deactivation"),
                    ("moderator_suspension", "Moderator suspension"),
                    ("moderator_deletion", "Moderator deletion"),
                    ("domain_block", "Domain block"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
