# Generated by Django 3.2.15 on 2022-10-05 22:54

import bookwyrm.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0160_auto_20221005_2239"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genre",
            name="remote_id",
            field=bookwyrm.models.fields.RemoteIdField(
                max_length=255,
                null=True,
                validators=[bookwyrm.models.fields.validate_remote_id],
            ),
        ),
        migrations.AddField(
            model_name="genre",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
