# Generated by Django 3.2.15 on 2022-09-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0160_auto_20220908_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='bookwyrm.Genre'),
        ),
    ]
