# Generated by Django 3.2.15 on 2022-09-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0160_genrenotification_immutablegenre'),
        ('bookwyrm', '0161_alter_book_genres'),
    ]

    operations = [
    ]
