# Generated by Django 3.2.15 on 2022-10-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0161_auto_20221005_2254"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="remote_id",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="updated_date",
        ),
    ]
