# Generated by Django 3.2.15 on 2022-11-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0160_auto_20221101_2251"),
        ("bookwyrm", "0162_importjob_task_id"),
    ]

    operations = []
