# Generated by Django 3.2.15 on 2022-09-10 15:59

import bookwyrm.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0163_followedgenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrenotification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genrenotification',
            name='remote_id',
            field=bookwyrm.models.fields.RemoteIdField(max_length=255, null=True, validators=[bookwyrm.models.fields.validate_remote_id]),
        ),
        migrations.AddField(
            model_name='genrenotification',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
