
# Generated by Django 3.2.16 on 2022-10-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0159_auto_20220924_0634"),
        ("bookwyrm", "0163_genre_remote_id"),
    ]

    operations = []
