# Generated by Django 3.2.16 on 2022-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0164_status_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviterequest",
            name="answer",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
