# Generated by Django 3.2.16 on 2022-10-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0164_merge_0159_auto_20220924_0634_0163_genre_remote_id"),
        ("bookwyrm", "0164_merge_20221031_1703"),
    ]

    operations = []
