# Generated by Django 3.2.16 on 2022-11-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0163_merge_0160_auto_20221101_2251_0162_importjob_task_id'),
        ('bookwyrm', '0164_merge_0159_auto_20220924_0634_0163_genre_remote_id'),
    ]

    operations = [
    ]
