# Generated by Django 3.2.16 on 2022-10-31 18:10

import bookwyrm.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0165_merge_20221031_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', bookwyrm.models.fields.CharField(max_length=40)),
                ('description', bookwyrm.models.fields.CharField(max_length=500)),
                ('votes', bookwyrm.models.fields.IntegerField(default=1)),
            ],
        ),
    ]
