# Generated by Django 3.2.16 on 2022-11-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0165_alter_inviterequest_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="imports_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
