# Generated by Django 3.2.15 on 2022-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0165_auto_20220910_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followedgenre',
            name='genre',
        ),
        migrations.AddField(
            model_name='followedgenre',
            name='genre',
            field=models.ManyToManyField(null=True, to='bookwyrm.Genre'),
        ),
    ]
