# Generated by Django 3.2.16 on 2022-11-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0165_merge_20221031_1802'),
        ('bookwyrm', '0165_minimumvotessetting_suggestedbookgenre_suggestedgenre'),
    ]

    operations = [
    ]
