# Generated by Django 3.2.16 on 2022-10-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0166_suggestedgenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumVotesSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_votes', models.IntegerField(default=10)),
            ],
        ),
    ]
