# Generated by Django 3.2.16 on 2022-11-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0166_sitesettings_imports_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="impressum",
            field=models.TextField(default="Add a impressum here."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_impressum",
            field=models.BooleanField(default=False),
        ),
    ]
