# Generated by Django 3.2.16 on 2022-11-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0165_merge_20221111_1703"),
        ("bookwyrm", "0166_merge_20221102_1737"),
    ]

    operations = []
