# Generated by Django 3.2.16 on 2022-11-26 17:55

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0166_sitesettings_imports_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="ao3_key",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="audiofic_key",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="ao3_key",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="audiofic_key",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="edition",
            name="physical_format",
            field=bookwyrm.models.fields.CharField(
                blank=True,
                choices=[
                    ("AudiobookFormat", "Audiobook"),
                    ("EBook", "eBook"),
                    ("GraphicNovel", "Graphic novel"),
                    ("Hardcover", "Hardcover"),
                    ("Paperback", "Paperback"),
                    ("EBook", "Fanfiction"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
