# Generated by Django 3.2.15 on 2022-09-15 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0166_auto_20220914_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followedgenre',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookwyrm.genre'),
        ),
    ]
