# Generated by Django 3.2.16 on 2022-12-05 17:01

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0167_auto_20221125_1900"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="aasin",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="aasin",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
