# Generated by Django 3.2.15 on 2022-09-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0167_auto_20220915_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedgenre',
            name='genres',
            field=models.ManyToManyField(blank=True, to='bookwyrm.Genre'),
        ),
    ]
