# Generated by Django 3.2.16 on 2022-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0167_auto_20221031_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='genres_url',
            field=models.CharField(default='https', max_length=255),
            preserve_default=False,
        ),
    ]
