# Generated by Django 3.2.15 on 2022-09-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0168_alter_followedgenre_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedgenre',
            name='genres',
            field=models.ManyToManyField(to='bookwyrm.Genre'),
        ),
    ]
