# Generated by Django 3.2.16 on 2022-11-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0163_merge_0160_auto_20221101_2251_0162_importjob_task_id'),
        ('bookwyrm', '0168_connector_genres_url'),
    ]

    operations = [
    ]
