# Generated by Django 3.2.16 on 2022-12-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0168_auto_20221205_2331"),
        ("bookwyrm", "0169_auto_20221206_0902"),
    ]

    operations = []
