# Generated by Django 3.2.16 on 2022-11-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0167_merge_20221111_1730'),
        ('bookwyrm', '0170_merge_20221111_1725'),
    ]

    operations = [
    ]
