# Generated by Django 3.2.15 on 2022-09-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0157_auto_20220909_2338'),
        ('bookwyrm', '0171_auto_20220917_1858'),
    ]

    operations = [
    ]
