# Generated by Django 3.2.16 on 2022-11-13 17:23

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0171_merge_20221113_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=bookwyrm.models.fields.CharField(max_length=500),
        ),
    ]
