# Generated by Django 3.2.16 on 2022-11-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0166_sitesettings_imports_enabled'),
        ('bookwyrm', '0171_merge_20221113_1722'),
        ('bookwyrm', '0171_merge_20221113_1810'),
    ]

    operations = [
    ]
