# Generated by Django 3.2.16 on 2022-12-28 14:36

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0172_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="website",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="isfdb",
            field=bookwyrm.models.fields.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="isni",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=19, null=True
            ),
        ),
    ]
