# Generated by Django 3.2.16 on 2022-12-26 18:13

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0172_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="audiobook_play_time",
            field=bookwyrm.models.fields.PermissivePlayTime(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
