# Generated by Django 3.2.16 on 2023-01-15 08:38

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0172_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="website",
            field=bookwyrm.models.fields.CharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
