# Generated by Django 3.2.16 on 2023-01-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0171_merge_20221219_2020"),
        ("bookwyrm", "0172_alter_user_preferred_language"),
    ]

    operations = []
