# Generated by Django 3.2.15 on 2022-09-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0172_merge_0157_auto_20220909_2338_0171_auto_20220917_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookwyrm.work'),
        ),
    ]
