# Generated by Django 3.2.16 on 2023-01-01 16:19

import bookwyrm.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0172_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="suggests_for",
            field=bookwyrm.models.fields.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suggestion_list",
                to="bookwyrm.edition",
            ),
        ),
    ]
