# Generated by Django 3.2.16 on 2023-01-01 12:26

import bookwyrm.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0172_alter_user_preferred_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionList",
            fields=[
                (
                    "list_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.list",
                    ),
                ),
                (
                    "book",
                    bookwyrm.models.fields.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bookwyrm.edition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.list",),
        ),
    ]
