# Generated by Django 3.2.18 on 2023-02-22 18:54

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_default_user_auth_group_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_published_loose_date',
            field=bookwyrm.models.fields.LooseDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_loose_date',
            field=bookwyrm.models.fields.LooseDateField(blank=True, null=True),
        ),
    ]
