# Generated by Django 3.2.16 on 2022-11-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0166_sitesettings_imports_enabled'),
        ('bookwyrm', '0173_merge_20221117_1523'),
    ]

    operations = [
    ]
