# Generated by Django 3.2.16 on 2022-11-18 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_merge_20221117_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedgenre',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
