# Generated by Django 3.2.15 on 2022-09-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0173_notification_related_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreNotification',
        ),
    ]
