# Generated by Django 3.2.16 on 2023-01-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0173_merge_20230102_1444"),
    ]

    operations = []
