# Generated by Django 3.2.16 on 2023-02-25 18:49

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0174_auto_20230222_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_published_date_precision',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date_precision',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=5, null=True),
        ),
    ]
