# Generated by Django 3.2.16 on 2022-11-18 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0174_suggestedgenre_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedbookgenre',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
