# Generated by Django 3.2.16 on 2023-01-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0173_author_website"),
        ("bookwyrm", "0174_merge_20230111_1523"),
    ]

    operations = []
