# Generated by Django 3.2.16 on 2022-11-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0174_merge_20221118_1557'),
        ('bookwyrm', '0175_suggestedbookgenre_users'),
    ]

    operations = [
    ]
