# Generated by Django 3.2.18 on 2023-03-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0174_auto_20230222_1742"),
        ("bookwyrm", "0176_hashtag_support"),
    ]

    operations = []
