# Generated by Django 3.2.18 on 2023-03-28 21:32

import bookwyrm.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bookwyrm", "0177_merge_0174_auto_20230222_1742_0176_hashtag_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=bookwyrm.models.fields.CICharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_user_auth_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-us", "English"),
                    ("ca-es", "Català (Catalan)"),
                    ("de-de", "Deutsch (German)"),
                    ("eo-uy", "Esperanto (Esperanto)"),
                    ("es-es", "Español (Spanish)"),
                    ("eu-es", "Euskara (Basque)"),
                    ("gl-es", "Galego (Galician)"),
                    ("it-it", "Italiano (Italian)"),
                    ("fi-fi", "Suomi (Finnish)"),
                    ("fr-fr", "Français (French)"),
                    ("lt-lt", "Lietuvių (Lithuanian)"),
                    ("no-no", "Norsk (Norwegian)"),
                    ("pl-pl", "Polski (Polish)"),
                    ("pt-br", "Português do Brasil (Brazilian Portuguese)"),
                    ("pt-pt", "Português Europeu (European Portuguese)"),
                    ("ro-ro", "Română (Romanian)"),
                    ("sv-se", "Svenska (Swedish)"),
                    ("zh-hans", "简体中文 (Simplified Chinese)"),
                    ("zh-hant", "繁體中文 (Traditional Chinese)"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
