# Generated by Django 3.2.18 on 2023-04-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0156_alter_bookauthor_table"),
        ("bookwyrm", "0178_auto_20230328_2132"),
    ]

    operations = []
