# Generated by Django 3.2.20 on 2023-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0179_populate_sort_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="audiobook_play_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
