# Generated by Django 3.2.18 on 2023-06-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0179_reportcomment_comment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportaction",
            options={"ordering": ("created_date",)},
        ),
    ]
