# Generated by Django 3.2.20 on 2023-08-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0180_alter_reportaction_options"),
        ("bookwyrm", "0180_alter_user_preferred_language"),
    ]

    operations = []
