# Generated by Django 3.2.20 on 2023-08-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0180_alter_bookauthor_author_type'),
        ('bookwyrm', '0181_merge_20230806_2302'),
    ]

    operations = [
    ]
