# Generated by Django 3.2.19 on 2023-09-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0179_bookwyrmexportjob_bookwyrmimportjob_childjob_parentjob"),
        ("bookwyrm", "0181_merge_20230806_2302"),
    ]

    operations = []
