# Generated by Django 3.2.20 on 2023-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0182_auto_20231027_1122"),
        ("bookwyrm", "0184_sitesettings_user_import_time_limit"),
    ]

    operations = []
