# Generated by Django 3.2.20 on 2023-11-09 16:57

import bookwyrm.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0184_auto_20231106_0421"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="first_published_date_precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAY", "Day seal"),
                    ("MONTH", "Month seal"),
                    ("YEAR", "Year seal"),
                ],
                editable=False,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="published_date_precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAY", "Day seal"),
                    ("MONTH", "Month seal"),
                    ("YEAR", "Year seal"),
                ],
                editable=False,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="first_published_date",
            field=bookwyrm.models.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=bookwyrm.models.fields.PartialDateField(blank=True, null=True),
        ),
    ]
