# Generated by Django 3.2.23 on 2023-11-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0184_auto_20231106_0421"),
        ("bookwyrm", "0186_alter_notification_notification_type"),
    ]

    operations = []
