# Generated by Django 3.2.23 on 2023-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0188_theme_loads"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="create_shelves",
            field=models.BooleanField(default=True),
        ),
    ]
