# Generated by Django 3.2.23 on 2023-11-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0186_auto_20231116_0048"),
        ("bookwyrm", "0188_theme_loads"),
    ]

    operations = []
