# Generated by Django 3.2.20 on 2023-11-24 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookwyrm", "0188_theme_loads"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="author",
            name="bookwyrm_au_search__b050a8_gin",
        ),
    ]
