# Generated by Django 3.2.23 on 2024-01-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0189_alter_user_preferred_language"),
        ("bookwyrm", "0190_alter_notification_notification_type"),
    ]

    operations = []
