# Generated by Django 3.2.23 on 2024-01-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0191_merge_20240102_0326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="endposition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="position",
            field=models.TextField(blank=True, null=True),
        ),
    ]
