# Generated by Django 3.2.23 on 2024-01-02 21:56

import bookwyrm.models.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0191_merge_20240102_0326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="links",
            field=bookwyrm.models.fields.ManyToManyField(
                blank=True, to="bookwyrm.Link"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="note",
            field=bookwyrm.models.fields.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=bookwyrm.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reporter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=bookwyrm.models.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookwyrm.status",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="user",
            field=bookwyrm.models.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
