# Generated by Django 3.2.23 on 2024-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0191_merge_20240102_0326"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="user_exports_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
