# Generated by Django 3.2.23 on 2024-02-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0192_make_page_positions_text"),
        ("bookwyrm", "0192_sitesettings_user_exports_enabled"),
    ]

    operations = []
