# Generated by Django 3.2.23 on 2024-02-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0192_rename_version_sitesettings_available_version"),
        ("bookwyrm", "0192_sitesettings_user_exports_enabled"),
    ]

    operations = []
