# Generated by Django 3.2.23 on 2024-01-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0192_auto_20240102_2156"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="user",
            new_name="reported_user",
        ),
    ]
