# Generated by Django 3.2.23 on 2024-01-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0193_rename_user_report_reported_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="reporter",
            new_name="user",
        ),
    ]
