# Generated by Django 3.2.23 on 2024-01-02 23:10

import bookwyrm.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0194_rename_reporter_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="allow_broadcast",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="reported_user",
            field=bookwyrm.models.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reported_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="user",
            field=bookwyrm.models.fields.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
