# Generated by Django 3.2.24 on 2024-02-22 09:05

import bookwyrm.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0195_alter_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="merged_into",
            field=bookwyrm.models.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookwyrm.author",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="merged_into",
            field=bookwyrm.models.fields.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookwyrm.book",
            ),
        ),
    ]
