# Generated by Django 3.2.23 on 2024-03-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0193_auto_20240128_0249"),
        ("bookwyrm", "0195_alter_user_preferred_language"),
    ]

    operations = []
