# Generated by Django 3.2.25 on 2024-03-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0196_merge_20240318_1737"),
        ("bookwyrm", "0196_merge_pr3134_into_main"),
    ]

    operations = []
