# Generated by Django 3.2.24 on 2024-02-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0196_merge_pr3134_into_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergedBook",
            fields=[
                ("deleted_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "merged_into",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absorbed",
                        to="bookwyrm.book",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MergedAuthor",
            fields=[
                ("deleted_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "merged_into",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absorbed",
                        to="bookwyrm.author",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
