# Generated by Django 3.2.25 on 2024-03-26 11:37

import bookwyrm.models.bookwyrm_export_job
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0197_merge_20240324_0235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookwyrmexportjob",
            name="export_data",
            field=models.FileField(
                null=True,
                storage=bookwyrm.models.bookwyrm_export_job.select_exports_storage,
                upload_to="",
            ),
        ),
    ]
