# Generated by Django 3.2.25 on 2024-03-24 11:20

import bookwyrm.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0197_merge_20240324_0235"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookwyrmexportjob",
            old_name="export_data",
            new_name="export_data_file",
        ),
        migrations.AddField(
            model_name="bookwyrmexportjob",
            name="export_data_s3",
            field=models.FileField(
                null=True,
                storage=bookwyrm.storage_backends.ExportsS3Storage,
                upload_to="",
            ),
        ),
    ]
