# Generated by Django 3.2.25 on 2024-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0198_book_search_vector_author_aliases"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="status",
            index=models.Index(
                fields=["remote_id"], name="bookwyrm_st_remote__06aeba_idx"
            ),
        ),
    ]
