# Generated by Django 3.2.25 on 2024-04-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0195_auto_20240102_2310"),
        ("bookwyrm", "0199_status_bookwyrm_st_remote__06aeba_idx"),
    ]

    operations = []
