# Generated by Django 3.2.25 on 2024-03-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0199_merge_20240326_1217"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addfiletotar",
            name="childjob_ptr",
        ),
        migrations.RemoveField(
            model_name="addfiletotar",
            name="parent_export_job",
        ),
        migrations.DeleteModel(
            name="AddBookToUserExportJob",
        ),
        migrations.DeleteModel(
            name="AddFileToTar",
        ),
    ]
