# Generated by Django 3.2.25 on 2024-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0200_status_bookwyrm_st_thread__cf064f_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="keypair",
            index=models.Index(
                fields=["remote_id"], name="bookwyrm_ke_remote__472927_idx"
            ),
        ),
    ]
