# Generated by Django 3.2.25 on 2024-04-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0200_auto_20240327_1914"),
        ("bookwyrm", "0204_merge_20240409_1042"),
    ]

    operations = []
