# Generated by Django 4.2.11 on 2024-04-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0201_alter_hashtag_name_alter_user_localname"),
        ("bookwyrm", "0204_merge_20240409_1042"),
    ]

    operations = []
