# Generated by Django 4.2.11 on 2024-04-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0205_merge_20240410_2022"),
        ("bookwyrm", "0205_merge_20240413_0232"),
    ]

    operations = []
