# Generated by Django 4.2.11 on 2024-06-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0189_importjob_create_shelves"),
        ("bookwyrm", "0206_merge_20240415_1537"),
    ]

    operations = []
