# Generated by Django 4.2.15 on 2024-08-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0200_merge_20240403_1728"),
        ("bookwyrm", "0208_merge_0207_merge_20240629_0626_0207_sqlparse_update"),
    ]

    operations = []
