# Generated by Django 4.2.15 on 2024-08-26 01:12

import bookwyrm.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0208_merge_0207_merge_20240629_0626_0207_sqlparse_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="suggests_for",
            field=bookwyrm.models.fields.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suggestion_list",
                to="bookwyrm.edition",
            ),
        ),
    ]
