# Generated by Django 4.2.15 on 2024-08-24 23:28

from django.db import migrations, models
import django.db.models.deletion


def copy_status_field(apps, schema_editor):
    """Move the foreign key status to the new many to many field"""
    reports = apps.get_model("bookwyrm", "Report")
    db_alias = schema_editor.connection.alias
    for report in reports.objects.using(db_alias).filter(status__isnull=False):
        report.statuses.add(report.status)


def reverse_copy_status_field(apps, schema_editor):
    """Move the first status in the many to many to the old FK"""
    reports = apps.get_model("bookwyrm", "Report")
    db_alias = schema_editor.connection.alias
    for report in reports.objects.using(db_alias).filter(statuses__isnull=False):
        report.status = report.statuses.first()
        report.save(broadcast=False, updated_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0209_merge_20240824_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="statuses",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="status_intermediary_name",
                to="bookwyrm.status",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookwyrm.status",
            ),
        ),
        migrations.RunPython(copy_status_field, reverse_code=reverse_copy_status_field),
    ]
