# Generated by Django 4.2.15 on 2024-08-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0209_suggestionlist_alter_listitem_options_and_more"),
        ("bookwyrm", "0209_user_show_ratings"),
    ]

    operations = []
