# Generated by Django 4.2.15 on 2024-10-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0210_userrelationshipimport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimportbook",
            name="fail_reason",
        ),
        migrations.RemoveField(
            model_name="userimportpost",
            name="fail_reason",
        ),
        migrations.RemoveField(
            model_name="userrelationshipimport",
            name="fail_reason",
        ),
        migrations.AddField(
            model_name="childjob",
            name="fail_reason",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="parentjob",
            name="fail_reason",
            field=models.TextField(null=True),
        ),
    ]
