# Generated by Django 4.2.15 on 2024-08-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0210_report_statuses_alter_report_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="status",
        ),
        migrations.AlterField(
            model_name="report",
            name="statuses",
            field=models.ManyToManyField(blank=True, null=True, to="bookwyrm.status"),
        ),
    ]
