# Generated by Django 4.2.16 on 2025-03-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0211_author_finna_key_book_finna_key"),
        ("bookwyrm", "0211_remove_userimportbook_fail_reason_and_more"),
    ]

    operations = []
