# Generated by Django 4.2.22 on 2025-08-16 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0214_alter_edition_isbn_10_alter_edition_isbn_13"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanUpUserExportFilesJob",
            fields=[
                (
                    "parentjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.parentjob",
                    ),
                ),
                ("expiry_date", models.DateTimeField()),
                ("tasks", models.IntegerField(default=0)),
                ("completed_tasks", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.parentjob",),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="export_files_lifetime_hours",
            field=models.IntegerField(default=72),
        ),
    ]
