# Generated by Django 5.2.3 on 2025-06-24 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookwyrm",
            "0215_rename_userrelationshipimport_userimportrelationship_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="shelves",
            field=models.ManyToManyField(
                through="bookwyrm.ShelfBook",
                through_fields=("book", "shelf"),
                to="bookwyrm.shelf",
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="books",
            field=models.ManyToManyField(
                through="bookwyrm.ListItem",
                through_fields=("book_list", "book"),
                to="bookwyrm.edition",
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="books",
            field=models.ManyToManyField(
                through="bookwyrm.ShelfBook",
                through_fields=("shelf", "book"),
                to="bookwyrm.edition",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="favorites",
            field=models.ManyToManyField(
                related_name="user_favorites",
                through="bookwyrm.Favorite",
                through_fields=("status", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="blocks",
            field=models.ManyToManyField(
                related_name="blocked_by",
                through="bookwyrm.UserBlocks",
                through_fields=("user_subject", "user_object"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_statuses",
                through="bookwyrm.Favorite",
                through_fields=("user", "status"),
                to="bookwyrm.status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="follow_requests",
            field=models.ManyToManyField(
                related_name="follower_requests",
                through="bookwyrm.UserFollowRequest",
                through_fields=("user_subject", "user_object"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="following",
                through="bookwyrm.UserFollows",
                through_fields=("user_object", "user_subject"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
