# Generated by Django 5.2.3 on 2025-09-08 02:52

import bookwyrm.models.user_upload
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0216_alter_edition_shelves_alter_list_books_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.TextField()),
                ("original_content_type", models.TextField()),
                (
                    "file",
                    models.ImageField(
                        upload_to=bookwyrm.models.user_upload.user_directory_path
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
