# Generated by Django 5.2.3 on 2025-08-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0215_cleanupuserexportfilesjob_and_more"),
        ("bookwyrm", "0216_alter_edition_shelves_alter_list_books_and_more"),
    ]

    operations = []
