# Generated by Django 5.2.3 on 2025-09-19 03:44

import bookwyrm.models.user_upload
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0217_userupload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userupload",
            old_name="file",
            new_name="original_file",
        ),
        migrations.CreateModel(
            name="UserUploadVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_dimension", models.TextField()),
                (
                    "file",
                    models.ImageField(
                        upload_to=bookwyrm.models.user_upload.user_upload_version_directory_path
                    ),
                ),
                (
                    "user_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookwyrm.userupload",
                    ),
                ),
            ],
        ),
    ]
