# Generated by Django 5.2.3 on 2025-09-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0218_merge_0217_merge_20250816_0749_0217_usersession"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindMissingCoversJob",
            fields=[
                (
                    "parentjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookwyrm.parentjob",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("missing", "Missing"), ("wrong_path", "Wrong Path")],
                        default="missing",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("completed_tasks", models.IntegerField(default=0)),
                (
                    "editions",
                    models.ManyToManyField(
                        related_name="missing_covers_job", to="bookwyrm.edition"
                    ),
                ),
                (
                    "found_covers",
                    models.ManyToManyField(related_name="+", to="bookwyrm.edition"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("bookwyrm.parentjob",),
        ),
    ]
