# Generated by Django 5.2.3 on 2025-10-19 12:31

from django.db import migrations
from django.db.models.functions import Length


def fix_isbn10_entries(apps, schema_editor):
    Edition = apps.get_model("bookwyrm", "Edition")
    editions_to_fix = Edition.objects.annotate(isbn_10_length=Length("isbn_10")).filter(
        isbn_10_length__gt=10
    )

    for edition_to_fix in editions_to_fix:
        if edition_to_fix.isbn_10.endswith("11"):
            edition_to_fix.isbn_10 = edition_to_fix.isbn_10[:9] + "0"
            edition_to_fix.save(broadcast=False)


class Migration(migrations.Migration):
    dependencies = [
        ("bookwyrm", "0218_merge_0217_merge_20250816_0749_0217_usersession"),
    ]

    operations = [migrations.RunPython(fix_isbn10_entries)]
