# Generated by Django 5.2.3 on 2025-11-15 20:33

from django.db import migrations
from django.contrib.auth.hashers import make_password


def set_unusable_passwords(apps, schema_editor):
    user_model = apps.get_model("bookwyrm", "User")
    deleted_users = user_model.objects.filter(
        is_deleted=True, allow_reactivation=False, local=True
    )
    for user in deleted_users:
        user.password = make_password(None)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0219_datamigration_fix_isbn10_20251017_1810"),
    ]

    operations = [
        migrations.RunPython(
            set_unusable_passwords, reverse_code=migrations.RunPython.noop
        )
    ]
