# Generated by Django 5.2.3 on 2025-11-15 20:52

from django.db import migrations, models


def force_admin_reset(apps, schema_editor):
    user_model = apps.get_model("bookwyrm", "User")
    user_model.objects.filter(
        models.Q(groups__name__in=["moderator", "admin"]) | models.Q(is_superuser=True),
        is_active=True,
    ).distinct().update(force_password_reset=True)


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0220_auto_20251115_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_password_reset",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(force_admin_reset, reverse_code=migrations.RunPython.noop),
    ]
