# Generated by Django 5.2.3 on 2025-11-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0220_series_mergedseries_book_book_series_seriesbook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="book_series",
        ),
    ]
