# Generated by Django 5.2.3 on 2025-11-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0221_user_force_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="disable_federation",
            field=models.BooleanField(default=False),
        ),
    ]
