# Generated by Django 5.2.3 on 2025-11-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0221_remove_book_book_series"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seriesbook",
            options={},
        ),
    ]
