# Generated by Django 5.2.3 on 2025-11-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0222_merge_20251116_1831"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="disable_federation",
            field=models.BooleanField(default=False),
        ),
    ]
