# Generated by Django 5.2.9 on 2025-12-29 10:44

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BloomExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0223_sitesettings_disable_federation'),
    ]

    operations = [
        BloomExtension(),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.BloomIndex(fields=['remote_id', 'openlibrary_key', 'finna_key', 'inventaire_id', 'librarything_key', 'goodreads_key', 'bnf_id', 'viaf', 'wikidata', 'asin', 'aasin', 'isfdb'], name='bookwyrm_bo_remote__43009f_bloom'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=django.contrib.postgres.indexes.BloomIndex(fields=['isbn_10', 'isbn_13', 'oclc_number'], name='bookwyrm_ed_isbn_10_435a21_bloom'),
        ),
    ]
