# Generated by Django 5.2.9 on 2025-12-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0218_rename_file_userupload_original_file_and_more"),
        ("bookwyrm", "0223_sitesettings_disable_federation"),
    ]

    operations = []
