# Generated by Django 5.2.3 on 2025-11-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0219_alter_listitem_options_suggestionlist_and_more"),
        ("bookwyrm", "0223_sitesettings_disable_federation"),
    ]

    operations = []
