# Generated by Django 5.2.3 on 2025-11-19 04:37

import bookwyrm.models.activitypub_mixin
import bookwyrm.models.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0223_sitesettings_disable_federation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "remote_id",
                    bookwyrm.models.fields.RemoteIdField(
                        max_length=255,
                        null=True,
                        validators=[bookwyrm.models.fields.validate_remote_id],
                    ),
                ),
                ("origin_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "openlibrary_key",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "finna_key",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "inventaire_id",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "librarything_key",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "goodreads_key",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "bnf_id",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "viaf",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "wikidata",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "asin",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "aasin",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "isfdb",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("name", bookwyrm.models.fields.TextField(max_length=255)),
                (
                    "alternative_names",
                    bookwyrm.models.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "last_edited_by",
                    bookwyrm.models.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    bookwyrm.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(bookwyrm.models.activitypub_mixin.ObjectMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MergedSeries",
            fields=[
                ("deleted_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "merged_into",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absorbed",
                        to="bookwyrm.series",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeriesBook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "remote_id",
                    bookwyrm.models.fields.RemoteIdField(
                        max_length=255,
                        null=True,
                        validators=[bookwyrm.models.fields.validate_remote_id],
                    ),
                ),
                (
                    "series_number",
                    bookwyrm.models.fields.CharField(
                        blank=True, max_length=255, null=True
                    ),
                ),
                (
                    "book",
                    bookwyrm.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seriesbooks",
                        to="bookwyrm.book",
                    ),
                ),
                (
                    "series",
                    bookwyrm.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seriesbooks",
                        to="bookwyrm.series",
                    ),
                ),
                (
                    "user",
                    bookwyrm.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(bookwyrm.models.activitypub_mixin.ObjectMixin, models.Model),
        ),
    ]
