# Generated by Django 5.2.9 on 2025-12-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0224_user_newsletter_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_post_to_feed",
            field=models.BooleanField(default=True),
        ),
    ]
