# Generated by Django 5.2.9 on 2025-12-05

from django.db import migrations


def add_tufte_theme(apps, schema_editor):
    """Add Tufte-inspired theme"""
    db_alias = schema_editor.connection.alias
    theme_model = apps.get_model("bookwyrm", "Theme")
    theme_model.objects.using(db_alias).get_or_create(
        name="Tufte",
        path="css/themes/bookwyrm-tufte.scss",
    )


def remove_tufte_theme(apps, schema_editor):
    """Remove Tufte theme"""
    db_alias = schema_editor.connection.alias
    theme_model = apps.get_model("bookwyrm", "Theme")
    theme_model.objects.using(db_alias).filter(
        path="css/themes/bookwyrm-tufte.scss"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0225_user_default_post_to_feed"),
    ]

    operations = [
        migrations.RunPython(add_tufte_theme, remove_tufte_theme),
    ]
