# Generated by Django 5.2.9 on 2026-02-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookwyrm', '0227_edition_bookwyrm_ed_parent__c4f87c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='bookwyrm_us_is_acti_972dc4_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['local', 'is_active', 'last_active_date'], name='bookwyrm_us_local_40fe61_idx'),
        ),
    ]
