# Generated by Django 5.2.9 on 2026-02-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0218_rename_file_userupload_original_file_and_more"),
        ("bookwyrm", "0227_edition_bookwyrm_ed_parent__c4f87c_idx_and_more"),
    ]

    operations = []
