# Generated by Django 5.2.9 on 2026-02-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0224_series_mergedseries_seriesbook'),
        ('bookwyrm', '0227_edition_bookwyrm_ed_parent__c4f87c_idx_and_more'),
    ]

    operations = [
    ]
