# Generated by Django 5.2.9 on 2026-02-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0180_alter_bookauthor_author_type'),
        ('bookwyrm', '0227_edition_bookwyrm_ed_parent__c4f87c_idx_and_more'),
    ]

    operations = [
    ]
