# Generated by Django 5.2.9 on 2026-02-09 06:37

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_merge_20260209_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesbook',
            options={'ordering': ['series_number']},
        ),
        migrations.AddField(
            model_name='series',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='alternative_names',
            field=bookwyrm.models.fields.ArrayField(base_field=bookwyrm.models.fields.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
