# Generated by Django 5.2.9 on 2026-05-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_remove_user_bookwyrm_us_is_acti_972dc4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='block_incoming_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_login_everywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_signed_get',
            field=models.BooleanField(default=False),
        ),
    ]
