# Generated by Django 5.2.14 on 2026-05-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_remove_user_bookwyrm_us_is_acti_972dc4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='raw_notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
