# Generated by Django 5.2.9 on 2026-02-02 19:01

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_merge_20260202_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
    ]
