# Generated by Django 5.2.9 on 2026-04-25 07:17

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_remove_user_bookwyrm_us_is_acti_972dc4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True),
        ),
    ]
