# Generated by Django 5.2.9 on 2026-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_remove_user_bookwyrm_us_is_acti_972dc4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_books',
            field=models.ManyToManyField(related_name='blocked_by', to='bookwyrm.work'),
        ),
    ]
