# Generated by Django 5.2.9 on 2026-02-22 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0228_merge_20260222_0352"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_image_uploads",
                to="bookwyrm.status",
            ),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="useruploadversion",
            name="user_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="bookwyrm.userupload",
            ),
        ),
    ]
