# Generated by Django 5.2.9 on 2026-02-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0228_merge_20260203_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='bookwyrm.status'),
        ),
    ]
