# Generated by Django 5.2.14 on 2026-05-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_series_mergedseries_seriesbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedBook',
            new_name='MergedEdition',
        ),
        migrations.AlterField(
            model_name='mergededition',
            name='merged_into',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed', to='bookwyrm.edition'),
        ),
        migrations.CreateModel(
            name='MergedWork',
            fields=[
                ('deleted_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merged_into', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed', to='bookwyrm.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
