# Generated by Django 5.2.9 on 2026-02-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_series_libris_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesbook',
            options={'ordering': ['series_number']},
        ),
    ]
