# Generated by Django 5.2.14 on 2026-05-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_alter_review_name'),
        ('bookwyrm', '0229_series_mergedseries_seriesbook'),
    ]

    operations = [
    ]
