# Generated by Django 5.2.14 on 2026-05-20 16:37

import bookwyrm.models.activitypub_mixin
import bookwyrm.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_series_mergedseries_seriesbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', bookwyrm.models.fields.RemoteIdField(max_length=255, null=True, validators=[bookwyrm.models.fields.validate_remote_id])),
                ('embed_key', models.UUIDField(editable=False, null=True, unique=True)),
                ('privacy', bookwyrm.models.fields.PrivacyField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers'), ('direct', 'Private')], default='public', max_length=255)),
            ],
            options={
                'ordering': ('-updated_date',),
                'abstract': False,
            },
            bases=(bookwyrm.models.activitypub_mixin.OrderedCollectionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SuggestionListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', bookwyrm.models.fields.RemoteIdField(max_length=255, null=True, validators=[bookwyrm.models.fields.validate_remote_id])),
                ('notes', bookwyrm.models.fields.HtmlField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
            bases=(bookwyrm.models.activitypub_mixin.CollectionItemMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='list',
            name='bookwyrm_li_privacy_a38257_idx',
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='suggests_for',
            field=bookwyrm.models.fields.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_list', to='bookwyrm.work'),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='user',
            field=bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionlistitem',
            name='book',
            field=bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookwyrm.work'),
        ),
        migrations.AddField(
            model_name='suggestionlistitem',
            name='book_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookwyrm.suggestionlist'),
        ),
        migrations.AddField(
            model_name='suggestionlistitem',
            name='endorsement',
            field=models.ManyToManyField(related_name='suggestion_endorsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionlistitem',
            name='user',
            field=bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='books',
            field=models.ManyToManyField(through='bookwyrm.SuggestionListItem', through_fields=('book_list', 'book'), to='bookwyrm.work'),
        ),
        migrations.AlterUniqueTogether(
            name='suggestionlistitem',
            unique_together={('book', 'book_list')},
        ),
    ]
