# Generated by Django 5.2.14 on 2026-05-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0224_merge_20251116_1928'),
        ('bookwyrm', '0229_series_mergedseries_seriesbook'),
    ]

    operations = [
    ]
