# Generated by Django 5.2.9 on 2026-02-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_alter_seriesbook_options_series_libris_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriesbook',
            unique_together={('book', 'series')},
        ),
    ]
