# Generated by Django 5.2.14 on 2026-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0229_series_mergedseries_seriesbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='raw_notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
