# Generated by Django 5.2.9 on 2026-03-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0228_remove_user_bookwyrm_us_is_acti_972dc4_idx_and_more"),
        ("bookwyrm", "0229_userupload_status_and_more"),
    ]

    operations = []
