# Generated by Django 5.2.14 on 2026-05-22 22:31

import bookwyrm.models.book
import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0230_rename_mergedbook_mergededition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='aasin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='AASIN'),
        ),
        migrations.AlterField(
            model_name='author',
            name='asin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bnf_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='BNF ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='finna_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Finna key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='goodreads_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='GoodReads key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='inventaire_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Inventaire ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='librarything_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LibraryThing key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Libris key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='openlibrary_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='viaf',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='VIAF'),
        ),
        migrations.AlterField(
            model_name='author',
            name='wikidata',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='aasin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='AASIN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='asin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bnf_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='BNF ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='finna_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Finna key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='goodreads_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='GoodReads key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventaire_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Inventaire ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isfdb',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ISFDB ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='librarything_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LibraryThing key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Libris key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='openlibrary_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='viaf',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='VIAF'),
        ),
        migrations.AlterField(
            model_name='book',
            name='wikidata',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='isbn_10',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, validators=[bookwyrm.models.book.validate_isbn10], verbose_name='ISBN 10'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='isbn_13',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, validators=[bookwyrm.models.book.validate_isbn13], verbose_name='ISBN 13'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='oclc_number',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OCLC number'),
        ),
        migrations.AlterField(
            model_name='series',
            name='aasin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='AASIN'),
        ),
        migrations.AlterField(
            model_name='series',
            name='asin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='series',
            name='bnf_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='BNF ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='finna_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Finna key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='goodreads_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='GoodReads key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='inventaire_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Inventaire ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='isfdb',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ISFDB ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='librarything_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LibraryThing key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Libris key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='openlibrary_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='viaf',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='VIAF'),
        ),
        migrations.AlterField(
            model_name='series',
            name='wikidata',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='lccn',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LCCN'),
        ),
    ]
