# Generated by Django 5.2.14 on 2026-05-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0230_merge_20260522_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='block_incoming_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_login_nearly_everywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_signed_get',
            field=models.BooleanField(default=False),
        ),
    ]
