# Generated by Django 5.2.14 on 2026-05-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0230_merge_20260522_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_books',
            field=models.ManyToManyField(related_name='blocked_by', to='bookwyrm.work'),
        ),
    ]
