# Generated by Django 5.2.14 on 2026-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0230_suggestionlist_suggestionlistitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionlistitem',
            options={},
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='book',
            new_name='edition',
        ),
        migrations.RenameField(
            model_name='suggestionlistitem',
            old_name='book',
            new_name='work',
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('edition', 'book_list'), ('order', 'book_list')},
        ),
        migrations.AlterUniqueTogether(
            name='suggestionlistitem',
            unique_together={('work', 'book_list')},
        ),
        migrations.RemoveField(
            model_name='list',
            name='books',
        ),
        migrations.RemoveField(
            model_name='suggestionlist',
            name='books',
        ),
        migrations.AddField(
            model_name='list',
            name='editions',
            field=models.ManyToManyField(through='bookwyrm.ListItem', through_fields=('book_list', 'edition'), to='bookwyrm.edition'),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='works',
            field=models.ManyToManyField(through='bookwyrm.SuggestionListItem', through_fields=('book_list', 'work'), to='bookwyrm.work'),
        ),
    ]
