# Generated by Django 5.2.9 on 2026-02-08 07:19

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0230_alter_seriesbook_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='user',
        ),
        migrations.AlterField(
            model_name='series',
            name='alternative_names',
            field=bookwyrm.models.fields.ArrayField(base_field=bookwyrm.models.fields.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
