# Generated by Django 5.2.14 on 2026-05-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0231_sitesettings_block_incoming_search_and_more'),
        ('bookwyrm', '0231_user_blocked_books'),
    ]

    operations = [
    ]
