# Generated by Django 5.2.9 on 2026-05-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookwyrm", "0230_merge_20260326_0357"),
        ("bookwyrm", "0231_sitesettings_block_incoming_search_and_more"),
    ]

    operations = []
