# Generated by Django 5.2.14 on 2026-05-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0231_rename_mergedbook_mergededition_alter_author_aasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.edition'),
        ),
        migrations.AddField(
            model_name='series',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.series'),
        ),
        migrations.AddField(
            model_name='work',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.work'),
        ),
    ]
