# Generated by Django 5.2.14 on 2026-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0231_alter_suggestionlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['privacy', '-updated_date'], name='bookwyrm_li_privacy_a38257_idx'),
        ),
    ]
