# Generated by Django 5.2.14 on 2026-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0232_user_readwise_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_private',
            field=models.BooleanField(default=False),
        ),
    ]
