# Generated by Django 5.2.14 on 2026-06-09 16:38

import bookwyrm.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0232_user_readwise_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born_precision',
            field=models.CharField(blank=True, choices=[('DAY', 'Day prec.'), ('MONTH', 'Month prec.'), ('YEAR', 'Year prec.')], editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='died_precision',
            field=models.CharField(blank=True, choices=[('DAY', 'Day prec.'), ('MONTH', 'Month prec.'), ('YEAR', 'Year prec.')], editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='born',
            field=bookwyrm.models.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='died',
            field=bookwyrm.models.fields.PartialDateField(blank=True, null=True),
        ),
    ]
