# Generated by Django 5.2.14 on 2026-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0233_author_born_precision_author_died_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='raw_notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
