# Generated by Django 5.2.14 on 2026-06-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0234_listitem_raw_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_books',
            field=models.ManyToManyField(related_name='blocked_by', to='bookwyrm.work'),
        ),
    ]
