# Generated by Django 5.2.14 on 2026-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0235_merge_20260615_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_books',
            field=models.ManyToManyField(related_name='blocked_by', to='bookwyrm.work'),
        ),
    ]
