# Generated by Django 5.2.14 on 2026-06-16 19:20

import bookwyrm.models.book
import bookwyrm.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0236_user_blocked_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedBook',
            new_name='MergedEdition',
        ),
        migrations.AddField(
            model_name='author',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='prevent_automatic_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='prevent_automatic_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edition',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.edition'),
        ),
        migrations.AddField(
            model_name='series',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.series'),
        ),
        migrations.AddField(
            model_name='series',
            name='prevent_automatic_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.work'),
        ),
        migrations.AlterField(
            model_name='author',
            name='aasin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='AASIN'),
        ),
        migrations.AlterField(
            model_name='author',
            name='asin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bnf_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='BNF ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='finna_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Finna key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='goodreads_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='GoodReads key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='inventaire_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Inventaire ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='librarything_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LibraryThing key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Libris key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='openlibrary_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary key'),
        ),
        migrations.AlterField(
            model_name='author',
            name='viaf',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='VIAF'),
        ),
        migrations.AlterField(
            model_name='author',
            name='wikidata',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='aasin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='AASIN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='asin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bnf_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='BNF ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='finna_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Finna key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='goodreads_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='GoodReads key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventaire_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Inventaire ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isfdb',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ISFDB ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='librarything_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LibraryThing key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Libris key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='openlibrary_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary key'),
        ),
        migrations.AlterField(
            model_name='book',
            name='viaf',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='VIAF'),
        ),
        migrations.AlterField(
            model_name='book',
            name='wikidata',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='isbn_10',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, validators=[bookwyrm.models.book.validate_isbn10], verbose_name='ISBN 10'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='isbn_13',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, validators=[bookwyrm.models.book.validate_isbn13], verbose_name='ISBN 13'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='oclc_number',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OCLC number'),
        ),
        migrations.AlterField(
            model_name='mergededition',
            name='merged_into',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed', to='bookwyrm.edition'),
        ),
        migrations.AlterField(
            model_name='series',
            name='aasin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='AASIN'),
        ),
        migrations.AlterField(
            model_name='series',
            name='asin',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='series',
            name='bnf_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='BNF ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='finna_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Finna key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='goodreads_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='GoodReads key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='inventaire_id',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Inventaire ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='isfdb',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='ISFDB ID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='librarything_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LibraryThing key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='libris_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Libris key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='openlibrary_key',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='OpenLibrary key'),
        ),
        migrations.AlterField(
            model_name='series',
            name='viaf',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='VIAF'),
        ),
        migrations.AlterField(
            model_name='series',
            name='wikidata',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='lccn',
            field=bookwyrm.models.fields.CharField(blank=True, max_length=255, null=True, verbose_name='LCCN'),
        ),
        migrations.CreateModel(
            name='MergedWork',
            fields=[
                ('deleted_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merged_into', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absorbed', to='bookwyrm.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
