# Generated by Django 5.2.14 on 2026-06-15 19:21

import bookwyrm.models.activitypub_mixin
import bookwyrm.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0236_user_blocked_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={},
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='book',
            new_name='edition',
        ),
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('edition', 'book_list'), ('order', 'book_list')},
        ),
        migrations.RemoveField(
            model_name='list',
            name='books',
        ),
        migrations.AddField(
            model_name='list',
            name='editions',
            field=models.ManyToManyField(through='bookwyrm.ListItem', through_fields=('book_list', 'edition'), to='bookwyrm.edition'),
        ),
        migrations.CreateModel(
            name='SuggestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', bookwyrm.models.fields.RemoteIdField(max_length=255, null=True, validators=[bookwyrm.models.fields.validate_remote_id])),
                ('embed_key', models.UUIDField(editable=False, null=True, unique=True)),
                ('privacy', bookwyrm.models.fields.PrivacyField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('followers', 'Followers'), ('direct', 'Private')], default='public', max_length=255)),
                ('suggests_for', bookwyrm.models.fields.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_list', to='bookwyrm.work')),
                ('user', bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_date',),
                'abstract': False,
            },
            bases=(bookwyrm.models.activitypub_mixin.OrderedCollectionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SuggestionListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', bookwyrm.models.fields.RemoteIdField(max_length=255, null=True, validators=[bookwyrm.models.fields.validate_remote_id])),
                ('notes', bookwyrm.models.fields.HtmlField(blank=True, max_length=300, null=True)),
                ('raw_notes', models.TextField(blank=True, max_length=300, null=True)),
                ('book_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookwyrm.suggestionlist')),
                ('endorsement', models.ManyToManyField(related_name='suggestion_endorsers', to=settings.AUTH_USER_MODEL)),
                ('user', bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work', bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookwyrm.work')),
            ],
            options={
                'unique_together': {('work', 'book_list')},
            },
            bases=(bookwyrm.models.activitypub_mixin.CollectionItemMixin, models.Model),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='works',
            field=models.ManyToManyField(through='bookwyrm.SuggestionListItem', through_fields=('book_list', 'work'), to='bookwyrm.work'),
        ),
    ]
