# Generated by Django 5.2.14 on 2026-06-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0236_user_blocked_books'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriesbook',
            unique_together={('book', 'series')},
        ),
    ]
