# Generated by Django 5.2.14 on 2026-06-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0155_book_new_authors'),
        ('bookwyrm', '0238_user_is_profile_private'),
    ]

    operations = [
    ]
