# Generated by Django 5.2.14 on 2026-06-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0237_rename_mergedbook_mergededition_and_more'),
        ('bookwyrm', '0239_alter_list_options_alter_listitem_options_and_more'),
    ]

    operations = [
    ]
