# Generated by Django 5.2.14 on 2026-06-24 23:45

import bookwyrm.models.user_upload
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0239_alter_list_options_alter_listitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.TextField()),
                ('original_content_type', models.TextField()),
                ('original_file', models.ImageField(upload_to=bookwyrm.models.user_upload.user_upload_directory_path)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image_uploads', to='bookwyrm.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_dimension', models.TextField()),
                ('file', models.ImageField(upload_to=bookwyrm.models.user_upload.user_upload_version_directory_path)),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bookwyrm.userupload')),
            ],
        ),
    ]
