# Generated by Django 5.2.14 on 2026-06-17 23:11

from django.db import migrations, models
import django.db.models.deletion
import bookwyrm.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0239_alter_list_options_alter_listitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "remote_id",
                    bookwyrm.models.fields.RemoteIdField(
                        max_length=255,
                        null=True,
                        validators=[bookwyrm.models.fields.validate_remote_id],
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("author", "Author"),
                            ("editor", "Editor"),
                            ("translator", "Translator"),
                            ("contributor", "Contributor"),
                            ("preface", "Author of Preface"),
                            ("illustrator", "Illustrator"),
                            ("letterer", "Letterer"),
                            ("narrator", "Narrator"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "author_type_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "author",
                    bookwyrm.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookwyrm.author",
                    ),
                ),
                (
                    "book",
                    bookwyrm.models.fields.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookwyrm.book"
                    ),
                ),
            ],
            options={
                "unique_together": {("book", "author", "author_type")},
            },
        ),
    ]
