# Generated by Django 5.2.14 on 2026-06-17 22:00

import bookwyrm.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0239_merge_20260617_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=bookwyrm.models.fields.ManyToManyField(through='bookwyrm.BookAuthor', through_fields=('book', 'author'), to='bookwyrm.author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='author_type',
            field=models.CharField(blank=True, choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('contributor', 'Contributor'), ('preface', 'Author of Preface'), ('illustrator', 'Illustrator'), ('letterer', 'Letterer'), ('narrator', 'Narrator'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='bookauthor',
            table='bookwyrm_book_authors',
        ),
    ]
