# Generated by Django 5.2.14 on 2026-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0240_userupload_useruploadversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='latest_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='most_recent_error',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='most_recent_success',
            field=models.DateTimeField(null=True),
        ),
    ]
