# Generated by Django 5.2.14 on 2026-06-27 21:51

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

def add_manage_data_perm(apps, schema_editor):
    """add manage_data perm if it doesn't exist"""

    User = apps.get_model("bookwyrm", "User")
    content_type = ContentType.objects.get_for_model(User)

    Permission.objects.get_or_create(
        codename="manage_data",
        name="manage data",
        content_type=content_type,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0240_merge_20260618_1833'),
    ]

    operations = [
        migrations.RunPython(add_manage_data_perm, reverse_code=migrations.RunPython.noop),
    ]
