# Generated by Django 5.2.15 on 2026-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0241_connector_latest_error_connector_most_recent_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='use_strict_ap_namespacing',
            field=models.BooleanField(default=False),
        ),
    ]
