# Generated by Django 5.2.14 on 2026-06-17 23:20

import bookwyrm.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0241_auto_20260617_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=bookwyrm.models.fields.ManyToManyField(through='bookwyrm.BookAuthor', through_fields=('book', 'author'), to='bookwyrm.author'),
        ),
        migrations.AlterModelTable(
            name='bookauthor',
            table='bookwyrm_book_authors',
        ),
    ]
