# Generated by Django 5.2.14 on 2026-07-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0241_auto_20260627_2151'),
        ('bookwyrm', '0241_connector_latest_error_connector_most_recent_error_and_more'),
    ]

    operations = [
    ]
