# Generated by Django 5.2.15 on 2026-07-29 10:23

import bookwyrm.models.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0241_connector_latest_error_connector_most_recent_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesbook',
            name='book',
            field=bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriesbooks', to='bookwyrm.work'),
        ),
    ]
