# Generated by Django 5.2.14 on 2026-07-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0242_merge_20260702_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'Edition', 'verbose_name_plural': 'Editions'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
    ]
