# Generated by Django 5.2.14 on 2026-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0242_merge_20260702_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suggestionlistitem',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterUniqueTogether(
            name='suggestionlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='prevent_automatic_merge',
            field=models.BooleanField(default=False),
        ),
    ]
