# Generated by Django 5.2.14 on 2026-07-25 00:11

import bookwyrm.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0242_alter_book_authors_alter_bookauthor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('remote_id', bookwyrm.models.fields.RemoteIdField(max_length=255, null=True, validators=[bookwyrm.models.fields.validate_remote_id])),
                ('contribution_type', models.CharField(choices=[('AO1', 'Author'), ('A07', 'Artist'), ('A08', 'Photographer'), ('A12', 'Illustrator'), ('A35', 'Drawer'), ('A36', 'Cover Artist'), ('A46', 'Inker'), ('A47', 'Colorist'), ('A48', 'Letterer'), ('A39', 'Map Maker'), ('EO3', 'Narrator (Audiobook)'), ('EO7', 'Reader (Audiobook)'), ('B01', 'Editor'), ('B09', 'Series Editor'), ('B04', 'Abridger'), ('B06', 'Translator'), ('A15', 'Preface Author'), ('A21', 'Commentaries Author'), ('A23', 'Foreword Author'), ('A99', 'Other')], default='AO1', max_length=3)),
                ('author', bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookwyrm.author')),
                ('book', bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookwyrm.book')),
            ],
            options={
                'db_table': 'bookwyrm_contributions',
                'unique_together': {('book', 'author', 'contribution_type')},
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=bookwyrm.models.fields.ManyToManyField(through='bookwyrm.Contribution', through_fields=('book', 'author'), to='bookwyrm.author'),
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
    ]
