# Generated by Django 5.2.15 on 2026-07-30 09:26

import json
from django.db import migrations
from bookwyrm.connectors import connector_manager


def fix_series(apps, schema_editor):
    """fix series from Inventaire borked due to bug"""

    Connector = apps.get_model("bookwyrm", "Connector")
    Work = apps.get_model("bookwyrm", "Work")
    Edition = apps.get_model("bookwyrm", "Edition")

    try:
        connector_info = Connector.objects.get(identifier="bookwyrm.social")
        connector = connector_manager.load_connector(connector_info)
        fixed_works = 0
        fixed_editions = 0

        works = Work.objects.filter(series__startswith="[")
        for work in works:
            if edition := work.editions.order_by("-edition_rank").first():
                try:
                    series = json.loads(work.series)
                    work.series = series
                    connector.get_or_create_seriesbook_from_data(
                        work=work, edition=edition
                    )
                    fixed_works += 1

                except (json.decoder.JSONDecodeError, TypeError):
                    # it's just a series name with a square bracket
                    # or it's not a recognisable series object
                    continue

            else:
                # childless work, just remove the series entry
                work.series = None
                work.series_number = None
                work.save()
                continue

        editions = Edition.objects.filter(series__startswith="[")
        for edition in editions:
            if not edition.parent_work:
                # orphaned edition, just remove the series entry
                edition.series = None
                edition.series_number = None
                edition.save()
                continue
            try:
                series = json.loads(edition.series)
                work = edition.parent_work
                work.series = series
                connector.get_or_create_seriesbook_from_data(work=work, edition=edition)
                fixed_editions += 1

            except (json.decoder.JSONDecodeError, TypeError):
                # it's just a series name with a square bracket
                # or it's not a recognisable series object
                continue

        print(
            f"Fixed {fixed_works} of {works.count()} works and {fixed_editions} of {editions.count()} editions with suspected stringified JSON series entries"
        )

    except Connector.DoesNotExist:
        print("Skipping series data fix - connectors not loaded yet")

class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0241_connector_latest_error_connector_most_recent_error_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_series, reverse_code=migrations.RunPython.noop),
    ]
