# Generated by Django 5.2.15 on 2026-07-17 23:25

import bookwyrm.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0243_alter_author_options_alter_edition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestionlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='suggestionlistitem',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterUniqueTogether(
            name='suggestionlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='pending_merge_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='pending_merge_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merge_target', to='bookwyrm.suggestionlist'),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='prevent_automatic_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestionlist',
            name='suggests_for',
            field=bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggests_for', to='bookwyrm.work'),
        ),
    ]
