# Generated by Django 5.2.16 on 2026-09-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0243_auto_20260730_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='user',
        ),
    ]
