# Generated by Django 5.2.16 on 2026-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0243_auto_20260730_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_post_status',
            field=models.BooleanField(default=True),
        ),
    ]
