# Generated by Django 5.2.14 on 2026-07-25 02:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0243_contribution_alter_book_authors_delete_bookauthor'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='author',
            name='reset_book_search_vector_on_author_edit',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='book',
            name='update_search_vector_on_book_edit',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='author',
            trigger=pgtrigger.compiler.Trigger(name='reset_book_search_vector_on_author_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func="WITH updated_books AS (SELECT book_id FROM bookwyrm_contributions WHERE author_id = new.id) UPDATE bookwyrm_book SET search_vector = '' FROM updated_books WHERE id = updated_books.book_id;RETURN NEW;", hash='9dfc9268465a25cb7942a24480a5492331aa1f94', operation='UPDATE OF "name", "aliases"', pgid='pgtrigger_reset_book_search_vector_on_author_edit_a50c7', table='bookwyrm_author', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='book',
            trigger=pgtrigger.compiler.Trigger(name='update_search_vector_on_book_edit', sql=pgtrigger.compiler.UpsertTriggerSql(func="WITH author_names AS (SELECT array_to_string(bookwyrm_author.name || bookwyrm_author.aliases, ' ') AS name_and_aliases FROM bookwyrm_author LEFT JOIN bookwyrm_contributions ON bookwyrm_author.id = bookwyrm_contributions.author_id WHERE bookwyrm_contributions.book_id = new.id) SELECT setweight(coalesce(nullif(to_tsvector('english', new.title), ''), to_tsvector('simple', new.title)), 'A') || setweight(to_tsvector('english', coalesce(new.subtitle, '')), 'B') || (SELECT setweight(to_tsvector('simple', coalesce(array_to_string(array_agg(name_and_aliases), ' '), '')), 'C') FROM author_names) || setweight(to_tsvector('english', coalesce(new.series, '')), 'D') INTO new.search_vector;RETURN NEW;", hash='4b6cd0a194ef47506618c4958940d711cabf1882', operation='INSERT OR UPDATE OF "title", "subtitle", "series", "search_vector"', pgid='pgtrigger_update_search_vector_on_book_edit_bec58', table='bookwyrm_book', when='BEFORE')),
        ),
    ]
