# Generated by Django 5.2.16 on 2026-08-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0243_auto_20260730_0926'),
        ('bookwyrm', '0244_alter_suggestionlist_options_and_more'),
    ]

    operations = [
    ]
