# Generated by Django 5.2.16 on 2026-09-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0243_auto_20260730_0926'),
        ('bookwyrm', '0244_remove_author_reset_book_search_vector_on_author_edit_and_more'),
    ]

    operations = [
    ]
