# Generated by Django 5.2.16 on 2026-08-29 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0245_merge_20260820_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='prevent_automatic_merge_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_prevented_merges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='prevent_automatic_merge_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_prevented_merges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='prevent_automatic_merge_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_prevented_merges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestionlist',
            name='prevent_automatic_merge_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_prevented_merges', to=settings.AUTH_USER_MODEL),
        ),
    ]
