# Generated by Django 5.2.16 on 2026-09-12 00:17

import bookwyrm.models.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0246_author_prevent_automatic_merge_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfbook',
            name='book',
            field=bookwyrm.models.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookwyrm.edition'),
        ),
    ]
