# Generated by Django 5.2.16 on 2026-09-12 18:20

from django.db import migrations, models
from django.db.models import Count, Subquery, OuterRef

def set_read_count(apps, schema_editor):
    """ how many readthroughs go back to this work"""
    Work = apps.get_model("bookwyrm", "Work")
    Work.objects.filter(editions__isnull=False).update(
        read_count=Subquery(
            Work.objects.filter(id=OuterRef("id")).annotate(
                reads=Count("editions__readthrough")
            ).values_list("reads", flat=True)
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0247_alter_shelfbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_read_count, reverse_code=migrations.RunPython.noop),
    ]
