# Generated by Django 5.2.16 on 2026-09-20 08:22

from django.db import migrations

def update_openlibrary_url(apps, schema_editor):
    """fix openlibrary search_url"""

    Connector = apps.get_model("bookwyrm", "Connector")
    if connector := Connector.objects.filter(identifier="openlibrary.org").first():
        if connector.search_url == "https://openlibrary.org/search?q=":
            connector.search_url = "https://openlibrary.org/search.json?q="
            connector.save(update_fields=["search_url"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0247_alter_shelfbook_book'),
    ]

    operations = [
        migrations.RunPython(update_openlibrary_url)
    ]
