# Generated by Django 5.2.16 on 2026-09-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookwyrm', '0248_update_openlibrary_search_url'),
        ('bookwyrm', '0248_work_read_count'),
    ]

    operations = [
    ]
