# Generated by Django 3.0.3 on 2020-03-07 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0008_auto_20200224_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
