# Generated by Django 3.0.3 on 2020-03-08 16:25

from django.db import migrations, models
import fedireads.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='aliases',
            field=fedireads.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
