# Generated by Django 3.0.3 on 2020-03-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0017_auto_20200314_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='remote_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
