# Generated by Django 3.0.3 on 2020-03-27 23:35

from django.db import migrations, models
import django.db.models.deletion
import fedireads.models.book


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0019_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('connector_file', models.CharField(choices=[('openlibrary', 'Openlibrary'), ('fedireads', 'Fedireads')], default='openlibrary', max_length=255)),
                ('is_self', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=255, null=True)),
                ('base_url', models.CharField(max_length=255)),
                ('covers_url', models.CharField(max_length=255)),
                ('search_url', models.CharField(max_length=255, null=True)),
                ('key_name', models.CharField(max_length=255)),
                ('politeness_delay', models.IntegerField(null=True)),
                ('max_query_count', models.IntegerField(null=True)),
                ('query_count', models.IntegerField(default=0)),
                ('query_count_expiry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='local_key',
            new_name='fedireads_key',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='origin',
            new_name='source_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='local_edits',
        ),
        migrations.AddConstraint(
            model_name='connector',
            constraint=models.CheckConstraint(check=models.Q(connector_file__in=fedireads.models.book.ConnectorFiles), name='connector_file_valid'),
        ),
        migrations.AddField(
            model_name='book',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fedireads.Connector'),
        ),
    ]
