# Generated by Django 3.0.3 on 2020-03-30 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0024_federatedserver_application_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_sync_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
