# Generated by Django 3.0.3 on 2020-03-30 19:43

from django.db import migrations, models
import fedireads.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0025_auto_20200330_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=fedireads.utils.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='edition',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
