# Generated by Django 3.0.3 on 2020-03-30 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0026_auto_20200330_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='parent_work',
        ),
        migrations.RemoveField(
            model_name='book',
            name='shelves',
        ),
        migrations.AddField(
            model_name='edition',
            name='parent_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fedireads.Work'),
        ),
        migrations.AddField(
            model_name='edition',
            name='shelves',
            field=models.ManyToManyField(through='fedireads.ShelfBook', to='fedireads.Shelf'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fedireads.Edition'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fedireads.Edition'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fedireads.Edition'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(through='fedireads.ShelfBook', to='fedireads.Edition'),
        ),
        migrations.AlterField(
            model_name='shelfbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fedireads.Edition'),
        ),
        migrations.AlterField(
            model_name='status',
            name='mention_books',
            field=models.ManyToManyField(related_name='mention_book', to='fedireads.Edition'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fedireads.Edition'),
        ),
    ]
