# Generated by Django 3.0.3 on 2020-05-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0035_auto_20200429_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='books_url',
            field=models.CharField(default='https://openlibrary.org', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='priority',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='connector',
            name='self',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_file',
            field=models.CharField(choices=[('openlibrary', 'Openlibrary'), ('self_connector', 'Self Connector'), ('fedireads_connector', 'Fedireads Connector')], max_length=255),
        ),
    ]
