# Generated by Django 3.0.3 on 2020-05-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0036_auto_20200503_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='fedireads_key',
        ),
        migrations.RemoveField(
            model_name='book',
            name='fedireads_key',
        ),
    ]
