# Generated by Django 3.0.3 on 2020-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0041_user_remote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wyrms.cthulahoops.org', max_length=100)),
                ('instance_description', models.TextField(default='This instance has no description.')),
                ('code_of_conduct', models.TextField(default='Add a code of conduct here.')),
                ('allow_registration', models.BooleanField(default=True)),
            ],
        ),
    ]
