# Generated by Django 3.0.7 on 2020-08-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedireads', '0044_siteinvite_user'),
        ('fedireads', '0042_auto_20200524_0346'),
    ]

    operations = [
    ]
