name: Container building for release

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag for build results"
        type: string
        default: manual
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      packages: write # to upload build to GHCR
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Work out Docker tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ inputs.tag }},event=workflow_dispatch
            type=semver,pattern={{version}}
            type=ref,event=pr
            type=ref,event=branch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ steps.docker_meta.outputs.version }}
            GIT_SHA=${{ github.sha }}
            DOCKER_TAG=${{ steps.docker_meta.outputs.tags }}
