name: Mypy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with mypy
      env:
        SECRET_KEY: beepbeep
        DEBUG: false
        USE_HTTPS: true
        DOMAIN: your.domain.here
        BOOKWYRM_DATABASE_BACKEND: postgres
        MEDIA_ROOT: images/
        POSTGRES_PASSWORD: hunter2
        POSTGRES_USER: postgres
        POSTGRES_DB: github_actions
        POSTGRES_HOST: 127.0.0.1
        CELERY_BROKER: ""
        REDIS_BROKER_PORT: 6379
        REDIS_BROKER_PASSWORD: beep
        USE_DUMMY_CACHE: true
        FLOWER_PORT: 8888
        EMAIL_HOST: "smtp.mailgun.org"
        EMAIL_PORT: 587
        EMAIL_HOST_USER: ""
        EMAIL_HOST_PASSWORD: ""
        EMAIL_USE_TLS: true
        ENABLE_PREVIEW_IMAGES: false
        ENABLE_THUMBNAIL_GENERATION: true
        HTTP_X_FORWARDED_PROTO: false
      run: |
        mypy bookwyrm celerywyrm
